C     ---------------------------------------
C
C     DSS LENGTHS AND SIZES COMMON BLOCK
C
      integer NCPW, NCMW, NWPW, NRECL, NSECRC, NPROGC, NPROG,
     * NDSSC, NDSS, NVERSC, NVERS, NTAGC, NTAG, NPFLAG, NDATEC,
     * NDATE, NTIMEC, NTIME, NKEY, NPERM, NLBIN, NINFO, NFILES, NUNIT,
     * NLDATA, NCOMP, NTAGBK, ICOMP, IQUAL, IDUNIT, NSIZE, NPASSC,
     * NPASS, JEOFFL, MEMSIZE
C
      COMMON /ZDSSNZ/ NCPW, NCMW, NWPW, NRECL, NSECRC, NPROGC, NPROG,
     * NDSSC, NDSS, NVERSC, NVERS, NTAGC, NTAG, NPFLAG, NDATEC,
     * NDATE, NTIMEC, NTIME, NKEY, NPERM, NLBIN, NINFO, NFILES, NUNIT,
     * NLDATA, NCOMP, NTAGBK, ICOMP, IQUAL, IDUNIT, NSIZE, NPASSC,
     * NPASS, JEOFFL, MEMSIZE
C
      REAL TOL
      COMMON /ZDSSRZ/ TOL
C
C     ---------------------------------------

