C     ---------------------------------------
C
C     DSS Logical variables common block
      LOGICAL LDELET, LDUNIT, LEXCL, LWLOCK, LFDATE, LINTAB, LTSCMP
      LOGICAL LREAD, LWRITE, LSZSET, LSTABL, LUNDEL, LBWRIT, LPROTC
      LOGICAL LSQSTA, LCATST, LREADO, LCOFIL, LTOL, LNOABT, LMULTU
      LOGICAL LUPRTIME, LQPBIT, LSHOWHANDL, LMEMORY, L8GB, LPSEUDO
	  LOGICAL LCPEMPTY, LFSQUEEZE
C
      COMMON /ZDSSLZ/  LDELET, LDUNIT, LEXCL, LWLOCK, LBWRIT, LREAD,
     * LWRITE, LFDATE, LINTAB, LSZSET, LSTABL, LUNDEL, LTSCMP, LPROTC,
     * LSQSTA, LCATST, LREADO, LCOFIL, LTOL, LNOABT, LMULTU, LUPRTIME,
     * LQPBIT, LSHOWHANDL, LMEMORY, L8GB, LPSEUDO, LCPEMPTY, LFSQUEEZE
C
C     ---------------------------------------

