#define IVERTICAL_DATUM_UNSET  0
#define IVERTICAL_DATUM_NAVD88 1
#define IVERTICAL_DATUM_NGVD29 2
#define IVERTICAL_DATUM_OTHER  3
#define IVERTICAL_DATUM_LOCAL  IVERTICAL_DATUM_OTHER

#define CVERTICAL_DATUM_UNSET  "UNSET"
#define CVERTICAL_DATUM_NAVD88 "NAVD-88"
#define CVERTICAL_DATUM_NGVD29 "NGVD-29"
#define CVERTICAL_DATUM_OTHER  "OTHER"
#define CVERTICAL_DATUM_LOCAL  CVERTICAL_DATUM_OTHER
