#
#  Dss-Fortran testing makefile for Solaris
#
FFLAGS= -m64  -xmemalign=2i -c -fpp -mt -xcode=pic32 -xpagesize=4M -O
FORTRAN=f95
HLIBS=../../heclib/heclib_f/Output/libhec_f.a ../../heclib/heclib_c/Output/libhec_c.a

CFLAGS=-m64 -c -I../../heclib/heclib_c/src/headers -I. -mt -xcode=pic32 -xstrconst -xc99=all -xCC -g -xs 
.PHONY: dss
dss:
	(cd ../../heclib; gmake )
	mkdir -p Output

# get predefinde symbols
# touch foo.f90; gfortran -cpp -E -dM foo.f90

interop: interop_c.c interop_f.f
	rm -f interop
	$(FORTRAN) -dM -c -g -cpp -m64 -fPIC -Wall interop_f.f
	cc $(CFLAGS) interop_c.c 
	$(FORTRAN) -m64 -fPIC   interop_c.o interop_f.o -o interop -lz -lrt -lgfortran -lm 
	./interop

all:dss Dss-Fortran

clean:
	$(RM) Output/*.o

test:dss Dss-Fortran
	rm -f Output/*.dss
	cp ../../dss-test-data/*.dss ./Output/
	(cd Output; ./Dss-Fortran)
#	(cd Output; valgrind --track-origins=yes  --log-file=vg.txt ./Dss-Fortran)


Output/DssCodeTest7.o:source/DssCodeTest7.f90
	$(FORTRAN) $(FFLAGS) source/DssCodeTest7.f90 -o Output/DssCodeTest7.o
Output/miscTests.o:source/miscTests.f90
	$(FORTRAN) $(FFLAGS) source/miscTests.f90 -o Output/miscTests.o
Output/orderTimes.o:source/orderTimes.f90
	$(FORTRAN) $(FFLAGS) source/orderTimes.f90 -o Output/orderTimes.o
Output/runTests.o:source/runTests.f90
	$(FORTRAN) $(FFLAGS) source/runTests.f90 -o Output/runTests.o
Output/saveToTextFile.o:./source/saveToTextFile.f90
	$(FORTRAN) $(FFLAGS) ./source/saveToTextFile.f90 -o Output/saveToTextFile.o
Output/test_conversion.o:source/test_conversion.f90
	$(FORTRAN) $(FFLAGS) source/test_conversion.f90 -o Output/test_conversion.o
Output/test_ITS_CharNotes.o:source/test_ITS_CharNotes.f90
	$(FORTRAN) $(FFLAGS) source/test_ITS_CharNotes.f90 -o Output/test_ITS_CharNotes.o
Output/test_ITS_CharNotesFull.o:source/test_ITS_CharNotesFull.f90
	$(FORTRAN) $(FFLAGS) source/test_ITS_CharNotesFull.f90 -o Output/test_ITS_CharNotesFull.o
Output/test_ITS_CharNotesLargerInt.o:source/test_ITS_CharNotesLargerInt.f90
	$(FORTRAN) $(FFLAGS) source/test_ITS_CharNotesLargerInt.f90 -o Output/test_ITS_CharNotesLargerInt.o
Output/test_ITS_CharNotesSameInt.o:source/test_ITS_CharNotesSameInt.f90
	$(FORTRAN) $(FFLAGS) source/test_ITS_CharNotesSameInt.f90 -o Output/test_ITS_CharNotesSameInt.o
Output/test_ITS_CharNotesSmallerInt.o:source/test_ITS_CharNotesSmallerInt.f90
	$(FORTRAN) $(FFLAGS) source/test_ITS_CharNotesSmallerInt.f90 -o Output/test_ITS_CharNotesSmallerInt.o
Output/test_ITS_Expansions.o:source/test_ITS_Expansions.f90
	$(FORTRAN) $(FFLAGS) source/test_ITS_Expansions.f90 -o Output/test_ITS_Expansions.o
Output/test_ITS_Full.o:source/test_ITS_Full.f90
	$(FORTRAN) $(FFLAGS) source/test_ITS_Full.f90 -o Output/test_ITS_Full.o
Output/test_ITS_Main.o:source/test_ITS_Main.f90
	$(FORTRAN) $(FFLAGS) source/test_ITS_Main.f90 -o Output/test_ITS_Main.o
Output/test_ITS_Qual.o:source/test_ITS_Qual.f90
	$(FORTRAN) $(FFLAGS) source/test_ITS_Qual.f90 -o Output/test_ITS_Qual.o
Output/test_ITS_Support.o:source/test_ITS_Support.f90
	$(FORTRAN) $(FFLAGS) source/test_ITS_Support.f90 -o Output/test_ITS_Support.o
Output/test_ITS_SupportCharNotes.o:source/test_ITS_SupportCharNotes.f90
	$(FORTRAN) $(FFLAGS) source/test_ITS_SupportCharNotes.f90 -o Output/test_ITS_SupportCharNotes.o
Output/test_RTS_AllSame.o:source/test_RTS_AllSame.f90
	$(FORTRAN) $(FFLAGS) source/test_RTS_AllSame.f90 -o Output/test_RTS_AllSame.o
Output/test_RTS_AllSameDouble.o:source/test_RTS_AllSameDouble.f90
	$(FORTRAN) $(FFLAGS) source/test_RTS_AllSameDouble.f90 -o Output/test_RTS_AllSameDouble.o
Output/test_RTS_AllSameDoubleToFloat.o:source/test_RTS_AllSameDoubleToFloat.f90
	$(FORTRAN) $(FFLAGS) source/test_RTS_AllSameDoubleToFloat.f90 -o Output/test_RTS_AllSameDoubleToFloat.o
Output/test_RTS_AllSameFloatsToDouble.o:source/test_RTS_AllSameFloatsToDouble.f90
	$(FORTRAN) $(FFLAGS) source/test_RTS_AllSameFloatsToDouble.f90 -o Output/test_RTS_AllSameFloatsToDouble.o
Output/test_RTS_AllSameQual.o:source/test_RTS_AllSameQual.f90
	$(FORTRAN) $(FFLAGS) source/test_RTS_AllSameQual.f90 -o Output/test_RTS_AllSameQual.o
Output/test_RTS_Basic.o:source/test_RTS_Basic.f90
	$(FORTRAN) $(FFLAGS) source/test_RTS_Basic.f90 -o Output/test_RTS_Basic.o
Output/test_RTS_CharNotes.o:source/test_RTS_CharNotes.f90
	$(FORTRAN) $(FFLAGS) source/test_RTS_CharNotes.f90 -o Output/test_RTS_CharNotes.o
Output/test_RTS_CharNotesBasic.o:source/test_RTS_CharNotesBasic.f90
	$(FORTRAN) $(FFLAGS) source/test_RTS_CharNotesBasic.f90 -o Output/test_RTS_CharNotesBasic.o
Output/test_RTS_CharNotesFull.o:source/test_RTS_CharNotesFull.f90
	$(FORTRAN) $(FFLAGS) source/test_RTS_CharNotesFull.f90 -o Output/test_RTS_CharNotesFull.o
Output/test_RTS_Double.o:source/test_RTS_Double.f90
	$(FORTRAN) $(FFLAGS) source/test_RTS_Double.f90 -o Output/test_RTS_Double.o
Output/test_RTS_DoubleQual.o:source/test_RTS_DoubleQual.f90
	$(FORTRAN) $(FFLAGS) source/test_RTS_DoubleQual.f90 -o Output/test_RTS_DoubleQual.o
Output/test_RTS_Expansions.o:source/test_RTS_Expansions.f90
	$(FORTRAN) $(FFLAGS) source/test_RTS_Expansions.f90 -o Output/test_RTS_Expansions.o
Output/test_RTS_Main.o:source/test_RTS_Main.f90
	$(FORTRAN) $(FFLAGS) source/test_RTS_Main.f90 -o Output/test_RTS_Main.o
Output/test_RTS_NoRepeats.o:source/test_RTS_NoRepeats.f90
	$(FORTRAN) $(FFLAGS) source/test_RTS_NoRepeats.f90 -o Output/test_RTS_NoRepeats.o
Output/test_RTS_NoRepeatsDoubleToFloat.o:source/test_RTS_NoRepeatsDoubleToFloat.f90
	$(FORTRAN) $(FFLAGS) source/test_RTS_NoRepeatsDoubleToFloat.f90 -o Output/test_RTS_NoRepeatsDoubleToFloat.o
Output/test_RTS_NoRepeatsFloatsToDouble.o:source/test_RTS_NoRepeatsFloatsToDouble.f90
	$(FORTRAN) $(FFLAGS) source/test_RTS_NoRepeatsFloatsToDouble.f90 -o Output/test_RTS_NoRepeatsFloatsToDouble.o
Output/test_RTS_NoRepeatsQual.o:source/test_RTS_NoRepeatsQual.f90
	$(FORTRAN) $(FFLAGS) source/test_RTS_NoRepeatsQual.f90 -o Output/test_RTS_NoRepeatsQual.o
Output/test_RTS_Repeats.o:source/test_RTS_Repeats.f90
	$(FORTRAN) $(FFLAGS) source/test_RTS_Repeats.f90 -o Output/test_RTS_Repeats.o
Output/test_RTS_RepeatsDoubleToFloat.o:source/test_RTS_RepeatsDoubleToFloat.f90
	$(FORTRAN) $(FFLAGS) source/test_RTS_RepeatsDoubleToFloat.f90 -o Output/test_RTS_RepeatsDoubleToFloat.o
Output/test_RTS_RepeatsFloatsToDouble.o:source/test_RTS_RepeatsFloatsToDouble.f90
	$(FORTRAN) $(FFLAGS) source/test_RTS_RepeatsFloatsToDouble.f90 -o Output/test_RTS_RepeatsFloatsToDouble.o
Output/test_RTS_RepeatsQual.o:source/test_RTS_RepeatsQual.f90
	$(FORTRAN) $(FFLAGS) source/test_RTS_RepeatsQual.f90 -o Output/test_RTS_RepeatsQual.o
Output/test_RTS_SecondIntervals.o:source/test_RTS_SecondIntervals.f90
	$(FORTRAN) $(FFLAGS) source/test_RTS_SecondIntervals.f90 -o Output/test_RTS_SecondIntervals.o
Output/testCatalog.o:source/testCatalog.f90
	$(FORTRAN) $(FFLAGS) source/testCatalog.f90 -o Output/testCatalog.o
Output/TestDss7.o:source/TestDss7.f90
	$(FORTRAN) $(FFLAGS) source/TestDss7.f90 -o Output/TestDss7.o
Output/testIrregRetClear.o:source/testIrregRetClear.f90
	$(FORTRAN) $(FFLAGS) source/testIrregRetClear.f90 -o Output/testIrregRetClear.o
Output/testOpen.o:source/testOpen.f90
	$(FORTRAN) $(FFLAGS) source/testOpen.f90 -o Output/testOpen.o
Output/testPairedData.o:source/testPairedData.f90
	$(FORTRAN) $(FFLAGS) source/testPairedData.f90 -o Output/testPairedData.o
Output/testReclaim.o:source/testReclaim.f90
	$(FORTRAN) $(FFLAGS) source/testReclaim.f90 -o Output/testReclaim.o
Output/testRegRetClear.o:source/testRegRetClear.f90
	$(FORTRAN) $(FFLAGS) source/testRegRetClear.f90 -o Output/testRegRetClear.o
Output/testUtilities.o:source/testUtilities.f90
	$(FORTRAN) $(FFLAGS) source/testUtilities.f90 -o Output/testUtilities.o
Output/testWrite.o:source/testWrite.f90
	$(FORTRAN) $(FFLAGS) source/testWrite.f90 -o Output/testWrite.o
Output/timeTestCopyRTS.o:source/timeTestCopyRTS.f90
	$(FORTRAN) $(FFLAGS) source/timeTestCopyRTS.f90 -o Output/timeTestCopyRTS.o
Output/timeTestFileParams.o:source/timeTestFileParams.f90
	$(FORTRAN) $(FFLAGS) source/timeTestFileParams.f90 -o Output/timeTestFileParams.o
Output/timeTestFileParamsRTS.o:source/timeTestFileParamsRTS.f90
	$(FORTRAN) $(FFLAGS) source/timeTestFileParamsRTS.f90 -o Output/timeTestFileParamsRTS.o
Output/timeTestRead.o:source/timeTestRead.f90
	$(FORTRAN) $(FFLAGS) source/timeTestRead.f90 -o Output/timeTestRead.o
Output/timeTestReadFile.o:source/timeTestReadFile.f90
	$(FORTRAN) $(FFLAGS) source/timeTestReadFile.f90 -o Output/timeTestReadFile.o
Output/timeTestReadFileRTS.o:source/timeTestReadFileRTS.f90
	$(FORTRAN) $(FFLAGS) source/timeTestReadFileRTS.f90 -o Output/timeTestReadFileRTS.o
Output/timeTestReadingRTS.o:source/timeTestReadingRTS.f90
	$(FORTRAN) $(FFLAGS) source/timeTestReadingRTS.f90 -o Output/timeTestReadingRTS.o
Output/timeTestWrite.o:source/timeTestWrite.f90
	$(FORTRAN) $(FFLAGS) source/timeTestWrite.f90 -o Output/timeTestWrite.o
Output/timeTestWriteFile.o:source/timeTestWriteFile.f90
	$(FORTRAN) $(FFLAGS) source/timeTestWriteFile.f90 -o Output/timeTestWriteFile.o
Output/timeTestWriteFileRTS.o:source/timeTestWriteFileRTS.f90
	$(FORTRAN) $(FFLAGS) source/timeTestWriteFileRTS.f90 -o Output/timeTestWriteFileRTS.o
Output/timeTestWritingRTS.o:source/timeTestWritingRTS.f90
	$(FORTRAN) $(FFLAGS) source/timeTestWritingRTS.f90 -o Output/timeTestWritingRTS.o
Output/writeARec.o:source/writeARec.f90
	$(FORTRAN) $(FFLAGS) source/writeARec.f90 -o Output/writeARec.o

OBJS=\
Output/DssCodeTest7.o\
Output/miscTests.o\
Output/orderTimes.o\
Output/runTests.o\
Output/saveToTextFile.o\
Output/test_conversion.o\
Output/test_ITS_CharNotes.o\
Output/test_ITS_CharNotesFull.o\
Output/test_ITS_CharNotesLargerInt.o\
Output/test_ITS_CharNotesSameInt.o\
Output/test_ITS_CharNotesSmallerInt.o\
Output/test_ITS_Expansions.o\
Output/test_ITS_Full.o\
Output/test_ITS_Main.o\
Output/test_ITS_Qual.o\
Output/test_ITS_Support.o\
Output/test_ITS_SupportCharNotes.o\
Output/test_RTS_AllSame.o\
Output/test_RTS_AllSameDouble.o\
Output/test_RTS_AllSameDoubleToFloat.o\
Output/test_RTS_AllSameFloatsToDouble.o\
Output/test_RTS_AllSameQual.o\
Output/test_RTS_Basic.o\
Output/test_RTS_CharNotes.o\
Output/test_RTS_CharNotesBasic.o\
Output/test_RTS_CharNotesFull.o\
Output/test_RTS_Double.o\
Output/test_RTS_DoubleQual.o\
Output/test_RTS_Expansions.o\
Output/test_RTS_Main.o\
Output/test_RTS_NoRepeats.o\
Output/test_RTS_NoRepeatsDoubleToFloat.o\
Output/test_RTS_NoRepeatsFloatsToDouble.o\
Output/test_RTS_NoRepeatsQual.o\
Output/test_RTS_Repeats.o\
Output/test_RTS_RepeatsDoubleToFloat.o\
Output/test_RTS_RepeatsFloatsToDouble.o\
Output/test_RTS_RepeatsQual.o\
Output/test_RTS_SecondIntervals.o\
Output/testCatalog.o\
Output/TestDss7.o\
Output/testIrregRetClear.o\
Output/testOpen.o\
Output/testPairedData.o\
Output/testReclaim.o\
Output/testRegRetClear.o\
Output/testUtilities.o\
Output/testWrite.o\
Output/timeTestCopyRTS.o\
Output/timeTestFileParams.o\
Output/timeTestFileParamsRTS.o\
Output/timeTestRead.o\
Output/timeTestReadFile.o\
Output/timeTestReadFileRTS.o\
Output/timeTestReadingRTS.o\
Output/timeTestWrite.o\
Output/timeTestWriteFile.o\
Output/timeTestWriteFileRTS.o\
Output/timeTestWritingRTS.o\
Output/writeARec.o



Dss-Fortran:$(OBJS)
	$(FORTRAN) -m64 -fPIC   Output/*.o ${HLIBS} ${HLIBS} ${HLIBS} -o Output/Dss-Fortran -lz -lrt -lm -lfsu 
