#include "hecdssInternal.h"

/**
*  Function:	zerrorDecode
*
*  Use:			Public
*
*  Description:	Part of the error processing functions, this decodes an error code to give
*					the severity, high function, low function, DSS error and status.
*					This function is usually called by the main program after an error has
*					been detected to inform the user of the actual error and where it occurred.
*
*  Called By:	various
*
*  Declaration: int zerrorDecode(int errorCode, int *highFunction, int *lowFunction, int *dssError, int *status);
*
*  Parameters:	int errorCode (input)
*					The error code to decode generated by zerrorProcessing or zerrorCodeHigh.
*
*				int *highFunction (output)
*					The function code of the highest calling function.  For example, this may tsStore.
*
*				int *lowFunction (output)
*					The function code of the lowest function, generally where the error actually occurred.
*						For example, this may be disk write.
*
*				int *dssError (output)
*					The DSS error number or code associated with this error
*
*				int *status  (output)
*					The system status or error associated with this.  For example, this may be a
*						system code that the file does not have write permission.
*
*
*	Returns:	int severity
*					The severity of this error, as defined in "zerrorCodes.h", with 1 being informational and 9 being critical.
*
*	Remarks:	Except for severity, each error code is 2 digits long (0-99).  Severity is only 1 digit (0-9)
*
*
*	Author:			Bill Charley
*	Date:			2014
*   Organization:	US Army Corps of Engineers, Hydrologic Engineering Center (USACE HEC)
*					All Rights Reserved
*
**/


int zerrorDecode(int errorCode, int *highFunction, int *lowFunction, int *dssError, int *status)
{

	int severity;

	if (errorCode < 0) {
		errorCode = -errorCode;
	}
	severity = errorCode / 100000000;
	*highFunction =  (errorCode - (severity * 100000000)) / 1000000;
	*lowFunction =  (errorCode - ((severity * 100000000) + (*highFunction * 1000000))) / 10000;
	*dssError =  (errorCode - ((severity * 100000000) + (*highFunction * 1000000) + (*lowFunction * 10000))) / 100;
	*status =  errorCode - ((severity * 100000000) + (*highFunction * 1000000) + (*lowFunction * 10000) + (*dssError * 100));
	return severity;
}



