#include "hecdssInternal.h"

/**
*  Function:	zerrorEncodeHigh
*
*  Use:			Private (Internal)
*
*  Description:	Part of the error processing functions, this adds the function code of the high level
*					function to the error code
*
*  Called By:	zerrorProcessing
*
*  Declaration: int  zerrorEncodeHigh(int errorCodeIn, int highFunction);
*
*  Parameters:	int errorCodeIn
*					The error code generated by zerrorProcessing and lower level functions.
*
*				int highFunction
*					The function code of the highest calling function.  For example, this may tsStore.
*
*
*	Returns:	int errorCode
*					The errorCode including the higher level function.
*
*	Author:			Bill Charley
*	Date:			2014
*   Organization:	US Army Corps of Engineers, Hydrologic Engineering Center (USACE HEC)
*					All Rights Reserved
*
**/


int zerrorEncodeHigh(int errorCodeIn, int highFunction)
{
	errorCodeIn +=  highFunction * 1000000;
	return errorCodeIn;
}


