#include "hecdssInternal.h"

/**
*  Function:	zerrorSeverity
*
*  Use:			Public
*
*  Description:	Returns the severity level of a DSS error.
*
*  Called By:	various
*
*  Declaration: int zerrorSeverity(int errorCode);
*
*  Parameters:	int errorCode (input)
*					The error code to decode generated by zerrorProcessing or zerrorCodeHigh.
*
*
*	Returns:	int severity
*					The severity of this error, as defined in "zerrorCodes.h", with 1 being informational and 9 being critical.
*
*	See Also:	zerrorDecode()
*
*
*	Author:			Bill Charley
*	Date:			2014
*   Organization:	US Army Corps of Engineers, Hydrologic Engineering Center (USACE HEC)
*					All Rights Reserved
*
**/


int zerrorSeverity(int errorCode)
{
	int severity;
	if (errorCode < 0) {
		errorCode = -errorCode;
	}
	severity = errorCode / 100000000;
	return severity;
}



