      SUBROUTINE zincbk (IBLOCK, JUL, IYR, IMON, IDAY)
C
      implicit none
C
      INTEGER IBLOCK, JUL, IYR, IMON, IDAY
C
      CALL ZINCBK7 (IBLOCK, JUL, IYR, IMON, IDAY)
C
      RETURN
      END

