      SUBROUTINE zofset (JULIAN, ITIME, INTERVAL, IFLAG, IOFSET)
C
      implicit none
C
      INTEGER JULIAN, ITIME, INTERVAL, IFLAG, IOFSET
C
      CALL zofset6(JULIAN, ITIME, INTERVAL, IFLAG, IOFSET)
C
      RETURN
      END

