      SUBROUTINE zritsc (IFLTAB, CPATH, JULS, ISTIME, JULE, IETIME,
     * LGETDOB, LFILDOB, ITIMES, SVALUES, DVALUES, KVALS, NVALS,
     * IBDATE, IQUAL, LQUAL, LQREAD, CUNITS, CTYPE, CSUPP,
     * ITZONE, CTZONE, COORDS, ICDESC, LCOORDS, INFLAG, ISTAT)
C
      implicit none
C
C
      INTEGER IFLTAB(*), IQUAL(*), ITIMES(*), ICDESC(*)
      REAL SVALUES(*)
      LOGICAL LQUAL, LQREAD, LGETDOB, LFILDOB, LCOORDS
C
      CHARACTER CPATH*(*), CUNITS*(*), CTYPE*(*)
	CHARACTER CTZONE*(*), CSUPP*(*)
C
      DOUBLE PRECISION DVALUES(*), COORDS(*)
      INTEGER JULS, ISTIME, JULE, IETIME, KVALS, NVALS
      INTEGER IBDATE, ITZONE, INFLAG, ISTAT
C
C
      IF (IFLTAB(1).EQ.6) THEN
         CALL zritsc6 (IFLTAB, CPATH, JULS, ISTIME, JULE, IETIME,
     *   LGETDOB, LFILDOB, ITIMES, SVALUES, DVALUES, KVALS, NVALS,
     *   IBDATE, IQUAL, LQUAL, LQREAD, CUNITS, CTYPE, CSUPP,
     *   ITZONE, CTZONE, COORDS, ICDESC, LCOORDS, INFLAG, ISTAT)
      ELSE
         CALL zritsc7 (IFLTAB, CPATH, JULS, ISTIME, JULE, IETIME,
     *   LGETDOB, LFILDOB, ITIMES, SVALUES, DVALUES, KVALS, NVALS,
     *   IBDATE, IQUAL, LQUAL, LQREAD, CUNITS, CTYPE, CSUPP,
     *   ITZONE, CTZONE, COORDS, ICDESC, LCOORDS, INFLAG, ISTAT)
      ENDIF
C
      RETURN
      END

