      SUBROUTINE ZRITSI (IFLTAB, CPATH, JULS, ISTIME, JULE, IETIME,
     * LGETDOB, LFILDOB, ITIMES, SVALUES, DVALUES, KVALS, NVALS,
     * IBDATE, IQUAL, LQUAL, LQREAD, CUNITS, CTYPE, IUHEAD, KUHEAD,
     * NUHEAD, COORDS, ICDESC, LCOORDS, INFLAG, ISTAT)
C
      implicit none
C
C
      INTEGER IFLTAB(*), IQUAL(*), ITIMES(*), IUHEAD(*), ICDESC(*)
      REAL SVALUES(*)
      DOUBLE PRECISION DVALUES(*), COORDS(*)
      LOGICAL LQUAL, LQREAD, LCOORDS
      LOGICAL LGETDOB, LFILDOB
      CHARACTER CPATH*(*), CUNITS*(*), CTYPE*(*)
      INTEGER JULS, ISTIME, JULE, IETIME, KVALS, NVALS
      INTEGER IBDATE, KUHEAD, NUHEAD, INFLAG, ISTAT
      integer zdssVersion
C
      IF (zdssVersion(IFLTAB).EQ.6) THEN
          CALL ZRITSI6 (IFLTAB, CPATH, JULS, ISTIME, JULE, IETIME,
     *    LGETDOB, LFILDOB, ITIMES, SVALUES, DVALUES, KVALS, NVALS,
     *    IBDATE, IQUAL, LQUAL, LQREAD, CUNITS, CTYPE, IUHEAD, KUHEAD,
     *    NUHEAD, COORDS, ICDESC, LCOORDS, INFLAG, ISTAT)
      ELSE
          CALL ZRITSI7 (IFLTAB, CPATH, JULS, ISTIME, JULE, IETIME,
     *    LGETDOB, LFILDOB, ITIMES, SVALUES, DVALUES, KVALS, NVALS,
     *    IBDATE, IQUAL, LQUAL, LQREAD, CUNITS, CTYPE, IUHEAD,
     *    KUHEAD, NUHEAD, COORDS, ICDESC, LCOORDS, INFLAG, ISTAT)
      ENDIF
C
      RETURN
      END

