      SUBROUTINE zsitsc(IFLTAB, CPATH, ITIMES, SVALUES, DVALUES,
     * LDOUBLE, NVALUE, IBDATE, JQUAL, LSQUAL, CUNITS, CTYPE,
     * COORDS, NCOORDS, ICDESC, NCDESC, CSUPP, ITZONE,
     * CTZONE, INFLAG, ISTAT)
C
      implicit none
C
C     Z - Store - IRregular - Time - Series  data into DSS database
C
      INTEGER IFLTAB(*), JQUAL(*), ITIMES(*)
      REAL SVALUES(*)
      DOUBLE PRECISION DVALUES(*), COORDS(*)
      INTEGER NVALUE, IBDATE, NCOORDS, ICDESC(*)
      INTEGER NCDESC, INFLAG, ISTAT, ITZONE
      LOGICAL LDOUBLE, LSQUAL
C
      CHARACTER CPATH*(*), CUNITS*(*), CTYPE*(*)
      CHARACTER CSUPP*(*), CTZONE*(*)
C
C
      IF (IFLTAB(1).EQ.6) THEN
         CALL zsitsc6(IFLTAB, CPATH, ITIMES, SVALUES, DVALUES,
     *   LDOUBLE, NVALUE, IBDATE, JQUAL, LSQUAL, CUNITS, CTYPE,
     *   COORDS, NCOORDS, ICDESC, NCDESC, CSUPP, ITZONE,
     *   CTZONE, INFLAG, ISTAT)
      ELSE
         CALL zsitsc7(IFLTAB, CPATH, ITIMES, SVALUES, DVALUES,
     *   LDOUBLE, NVALUE, IBDATE, JQUAL, LSQUAL, CUNITS, CTYPE,
     *   COORDS, NCOORDS, ICDESC, NCDESC, CSUPP, ITZONE,
     *   CTZONE, INFLAG, ISTAT)
      ENDIF
C
      RETURN
      END

