      SUBROUTINE zspdd (IFLTAB, CPATH, NORD, NCURVE, IHORIZ,
     * C1UNIT, C1TYPE, C2UNIT, C2TYPE, DVALUES, CLABEL, LABEL,
     * IUHEAD, NUHEAD, IPLAN, ISTAT)
C
      implicit none
      integer nord, ncurve, ihoriz, nuhead, iplan, istat
C
C     Store Paired DATA
C
C     Written by Bill Charley
C
C
      INTEGER IFLTAB(*), IUHEAD(*)
      CHARACTER CPATH*(*), CLABEL(*)*(*)
      CHARACTER C1UNIT*(*), C1TYPE*(*), C2UNIT*(*), C2TYPE*(*)
      REAL SVALUES(1)
      LOGICAL LABEL, LDOUBLE
      DOUBLE PRECISION DVALUES(*)
C
C
      LDOUBLE = .true.
      IF (IFLTAB(1).EQ.6) THEN
          CALL ZSPDI6 (IFLTAB, CPATH, NORD, NCURVE, IHORIZ,
     *    C1UNIT, C1TYPE, C2UNIT, C2TYPE, SVALUES, DVALUES,
     *    LDOUBLE, CLABEL, LABEL, IUHEAD, NUHEAD, IPLAN, ISTAT)
      ELSE
          CALL ZSPDI7 (IFLTAB, CPATH, NORD, NCURVE, IHORIZ,
     *    C1UNIT, C1TYPE, C2UNIT, C2TYPE, SVALUES, DVALUES,
     *    LDOUBLE, CLABEL, LABEL, IUHEAD, NUHEAD, IPLAN, ISTAT)
      ENDIF
C
      END

