      SUBROUTINE zspd (IFLTAB, CPATH, NORD, NCURVE, IHORIZ,
     * C1UNIT, C1TYPE, C2UNIT, C2TYPE, SVALUES, CLABEL, LABEL,
     * IUHEAD, NUHEAD, IPLAN, ISTAT)
C
      implicit none
C
C     Store Paired DATA
C
C     Written by Bill Charley
C
C
      INTEGER IFLTAB(*), IUHEAD(*)
      integer NORD,NCURVE,IHORIZ,NUHEAD,IPLAN,zdssVersion,ISTAT
      CHARACTER CPATH*(*), CLABEL(*)*(*)
      CHARACTER C1UNIT*(*), C1TYPE*(*), C2UNIT*(*), C2TYPE*(*)
      REAL SVALUES(*)
      LOGICAL LABEL, LDOUBLE
      DOUBLE PRECISION DVALUES(1)
C
C
      !write(*,*)'Enter zspd'
      !return


      LDOUBLE = .FALSE.
      IF (zdssVersion(IFLTAB).EQ.6) THEN
          CALL ZSPDI6 (IFLTAB, CPATH, NORD, NCURVE, IHORIZ,
     *    C1UNIT, C1TYPE, C2UNIT, C2TYPE, SVALUES, DVALUES,
     *    LDOUBLE, CLABEL, LABEL, IUHEAD, NUHEAD, IPLAN, ISTAT)
      ELSE
          CALL ZSPDI7 (IFLTAB, CPATH, NORD, NCURVE, IHORIZ,
     *    C1UNIT, C1TYPE, C2UNIT, C2TYPE, SVALUES, DVALUES,
     *    LDOUBLE, CLABEL, LABEL, IUHEAD, NUHEAD, IPLAN, ISTAT)
      ENDIF
C
      END

