      SUBROUTINE zsrtsc (IFLTAB, CPATH, CDATE, CTIME, NVALS,
     * LDOUBLE, SVALUES, DVALUES, JQUAL, LQUAL, CUNITS, CTYPE,
     * COORDS, NCOORDS, ICDESC, NCDESC, CSUPP, ITZONE,
     * CTZONE, IPLAN, JCOMP, BASEV, LBASEV, LDHIGH, NPREC, ISTAT)
C
      implicit none
C
C
C     Z-Store Regular interval Time-Series data Interface routine
C
C
C     Argument Dimensions
      CHARACTER CPATH*(*), CTYPE*(*), CUNITS*(*), CDATE*(*), CTIME*(*)
      CHARACTER CTZONE*(*), CSUPP*(*)
      INTEGER IFLTAB(*), JQUAL(*)
      INTEGER IPLAN, ISTAT, NVALS, ITZONE, NPREC, JCOMP
      LOGICAL LDOUBLE, LQUAL, LBASEV, LDHIGH
      REAL SVALUES(*), BASEV
      DOUBLE PRECISION DVALUES(*), COORDS(*)
      INTEGER NCDESC, NCOORDS, ICDESC(*)
C
      IF (IFLTAB(1).EQ.6) THEN
         CALL zsrtsc6 (IFLTAB, CPATH, CDATE, CTIME, NVALS,
     *   LDOUBLE, SVALUES, DVALUES, JQUAL, LQUAL, CUNITS, CTYPE,
     *   COORDS, NCOORDS, ICDESC, NCDESC, CSUPP, ITZONE,
     *   CTZONE, IPLAN, JCOMP, BASEV, LBASEV, LDHIGH, NPREC, ISTAT)
      ELSE
         CALL zsrtsc7 (IFLTAB, CPATH, CDATE, CTIME, NVALS,
     *   LDOUBLE, SVALUES, DVALUES, JQUAL, LQUAL, CUNITS, CTYPE,
     *   COORDS, NCOORDS, ICDESC, NCDESC, CSUPP, ITZONE,
     *   CTZONE, IPLAN, JCOMP, BASEV, LBASEV, LDHIGH, NPREC, ISTAT)
      ENDIF
C
      RETURN
      END

