      SUBROUTINE ZWRITX ( IFLTAB, CPATH, NPATH, IIHEAD, NIHEAD,
     * ICHEAD, NCHEAD, IUHEAD, NUHEAD, IDATA, NDATA, JTYPE,
     * IPLAN, ISTAT, LFOUND)
C
C     Deprecated
C
C     IPLAN = 0   Always write
C     IPLAN = 1   Only write if new record
C     IPLAN = 2   Only write if old record
C

      INTEGER IFLTAB(*)
      INTEGER IIHEAD(*), IDATA(*), ICHEAD(*), IUHEAD(*)
      INTEGER NPATH, NIHEAD, NCHEAD, NUHEAD, NDATA, JTYPE
      INTEGER IPLAN, ISTAT
      CHARACTER CPATH*(*)
      LOGICAL LFOUND
C
      CALL ZWRITEX ( IFLTAB, CPATH, NPATH, IIHEAD, NIHEAD,
     * ICHEAD, NCHEAD, IUHEAD, NUHEAD, IDATA, NDATA, JTYPE,
     * IPLAN, ISTAT, LFOUND)
C
C
      END

