      SUBROUTINE CHRFIL ( CLINE, CHR)
C
C     FILE CHARACTER ARRAY CLINE WITH CHARACTER CHR
C
      CHARACTER CLINE*(*), CHR*1
C
      NLEN = LEN(CLINE)
      DO 10 I=1,NLEN
      CLINE(I:I) = CHR(1:1)
 10   CONTINUE
C
      RETURN
      END

