      SUBROUTINE HOLCHR(IC,IS,NC,C,JS)
C
C     CONVERT FROM ALPHANUMERIC VARIABLE "IC" AND "NC" COUNT
C     TO CHARACTER VARIABLE "C" .
C     BEGIN AT "IS" AND "JS" RESPECTIVELY.
C
      CHARACTER C*(*)
      INTEGER IC(*)
C
C
C     MAKE SURE IWORDS IS INITIALIZED
      IF (IS.LT.0) CALL BKDATW
C
C     MOVE EACH CHARACTER FROM C TO IC
C
      J=JS-1
      DO 10 I=IS,IS+NC-1
      J=J+1
      CALL GETHOL(IC,I,ICH)
      C(J:J)=CHAR(ICH)
10    CONTINUE
      RETURN
      END

