      SUBROUTINE CHDLM (ITYPE,CSTRNG,IBEG,NUMB,ITBL)
C
C      CHDLM (CHANGE DELIMITERS) IS USED INTERNALLY BY
C      SETDLM, AND SHOULD NOT BE CALLED OTHERWISE.
C
      CHARACTER CSTRNG*(*)
      INTEGER ITBL(-1:126)
C
C     "ZERO OUT" OLD ITYPE DELIMS (WITH ONES)
C
      DO 10 I=0,126
          ITEMP = ITBL(I)/100
          IF (ITEMP.EQ.ITYPE) ITBL(I) = 1
10        CONTINUE
C
C     INSERT NEW DELIMITER VALUES
C
      DO 20 I = IBEG, NUMB
          ICH = ICHAR (CSTRNG(I:I))
C         ICH = IEB2AS (ICH)
          ITBL(ICH) = ITYPE*100 + I
20        CONTINUE
      RETURN
      END

