      SUBROUTINE DATIME(JYR,NDAY,J10SEC)
C
C
      CALL SYSTIM(JUL, ISEC)
      J10SEC = ISEC * 10
      I =  JLIYMD(JUL, JYR, IMON, IDAY)
      NDAY = JUL - IYMDJL(JYR, 1, 1) + 1
C
      RETURN
      END

