      SUBROUTINE MATCH (CSTR, IBEG, ILEN, CLIST, NLIST, NLEN, IMATCH)
C
C     SEARCH FOR STRING CSTR BEGINNING AT POSITION
C     IBEG AND ILEN CHARACTERS LONG.  IN CLIST
C     WHICH HAS NLIST ENTRIES EACH OF SIZE NLEN.
C     RETURN IMATCH - POSITION IN CLIST; 0 = NOT FOUND
C
      CHARACTER CSTR*(*), CLIST(NLIST)*(*)
      CHARACTER CTEMP1*200, CTEMP2*200
C
C
      IF (ILEN.LE.0) GO TO 20
      IEND = IBEG + ILEN - 1
      IF (IBEG.GT.IEND) GO TO 20
      CALL CHRLNB(CSTR, NSTR)
      CTEMP1 = CSTR(1:NSTR)
      CALL UPCASE(CTEMP1)
C
      DO 10 I=1,NLIST
      CALL CHRLNB(CLIST(I), NL)
      CTEMP2 = CLIST(I)(1:NL)
      CALL UPCASE(CTEMP2)
      IF(CTEMP1(IBEG:IEND).EQ.CTEMP2(1:ILEN)) THEN
      IMATCH  =  I
      RETURN
      ENDIF
 10   CONTINUE
C
 20   IMATCH = 0
      RETURN
      END

