      SUBROUTINE DSSCOPYSTATUS (NUMBRECS, NUMBPATHS, CURREC, CURPATH)
C
C
      INTEGER NUMBRECS, NUMBPATHS, CURREC, CURPATH
C
      COMMON /ZSTATUS/ TOTAL_NUMB,  CURRENT_NUMB,
     *                 INTERRUPT, NERROR, MAXERROR
      INTEGER TOTAL_NUMB,  CURRENT_NUMB,  INTERRUPT
C
      SAVE ALL
C
      NUMBRECS = TOTAL_NUMB
      NUMBPATHS = TOTAL_NUMB
      CURREC = CURRENT_NUMB
	CURPATH = CURRENT_NUMB
C
      RETURN
      END

