C     ---------------------------------------
C
C     DSS main pointers common block
C
C     NBSIZE is the record length (buffer size) in 32 bit integer words
      integer nbsize
      PARAMETER (NBSIZE=127)
C
      integer  KNV, KUNIT, KMULT, KPERM, KDSS, KNRECS, KFSIZE,
     * KHSIZE, KLOCK,  KDEAD,  KVERS, KCREAT, KLWDAT, KLWTIM, KTAGS,
     * KREADO, KHASH,  KTABLE, KBNBLK, KBNREM, KBNSIZ, KAFBIN, KSEQNO,
     * KANBIN, KFILEW, KPNHEA, KPNDAT, KLPFOU, KINTAB, KIQUAL,
     * KAINFO, KDTYPE, KLPATL, KLPATH, KBSTAT, KBNPAT,
     * KBPATH, KBAINF, KBNHEA, KBNDAT, KBTYPE, KBLNDA,
     * KBTAG,  KBPINTL, KIFLAG, KICOMP, KMXREC, KBSADD,
     * KISTAT, KINPAT, KIPATH, KIPASS, KMXPRT, KIUNUS,  KIADAT, KILNDA,
     * KINDAT, KITYPE, KIVER,  KIPROG, KIDATE, KITIME, KITAG,
     * KIAIHE, KINIHE, KIACHE, KINCHE, KIAUHE, KINUHE,
     * KIPREC, KPADD,  KPJBIN, KEY1,   KEY2,   KEY3,   KBHASH, KTAGBK,
     * KBINS,  KHUSED, KBOVER, KMAXPH, KMAXHC, KRBNPA, KRBHBE, KRBHEN,
     * KRBDBE, KRBDEN, KRBPAT, KWBNPA, KWBSIZ, KWBHAD, KWBDAD,
     * KWBPAT, KCOMPI, KCOMPN, KCOMP,  KHANDL, KFILES, KNAME,
     * KITSIN, KITSDA, KITSMO, KITSYE, KITSDE, KITSCE, KWLOCK,
     * KEXCL,  KSUSER, KFPASS, KLOCKB, KVERNO, KSWAP,  KSTAT, KLOCKR,
     * KMULT2, KMEMORY,KREMOTE,KDSWAP, KCOLL, KLOCKRD
C
      COMMON /ZDSSKZ/   KNV, KUNIT, KMULT, KPERM, KDSS, KNRECS, KFSIZE,
     * KHSIZE, KLOCK,  KDEAD,  KVERS, KCREAT, KLWDAT, KLWTIM, KTAGS,
     * KREADO, KHASH,  KTABLE, KBNBLK, KBNREM, KBNSIZ, KAFBIN, KSEQNO,
     * KANBIN, KFILEW, KPNHEA, KPNDAT, KLPFOU, KINTAB, KIQUAL,
     * KAINFO, KDTYPE, KLPATL, KLPATH, KBSTAT, KBNPAT,
     * KBPATH, KBAINF, KBNHEA, KBNDAT, KBTYPE, KBLNDA,
     * KBTAG,  KBPINTL, KIFLAG, KICOMP, KMXREC, KBSADD,
     * KISTAT, KINPAT, KIPATH, KIPASS, KMXPRT, KIUNUS,  KIADAT, KILNDA,
     * KINDAT, KITYPE, KIVER,  KIPROG, KIDATE, KITIME, KITAG,
     * KIAIHE, KINIHE, KIACHE, KINCHE, KIAUHE, KINUHE,
     * KIPREC, KPADD,  KPJBIN, KEY1,   KEY2,   KEY3,   KBHASH, KTAGBK,
     * KBINS,  KHUSED, KBOVER, KMAXPH, KMAXHC, KRBNPA, KRBHBE, KRBHEN,
     * KRBDBE, KRBDEN, KRBPAT, KWBNPA, KWBSIZ, KWBHAD, KWBDAD,
     * KWBPAT, KCOMPI, KCOMPN, KCOMP,  KHANDL, KFILES, KNAME,
     * KITSIN, KITSDA, KITSMO, KITSYE, KITSDE, KITSCE, KWLOCK,
     * KEXCL,  KSUSER, KFPASS, KLOCKB, KVERNO, KSWAP,  KSTAT, KLOCKR,
     * KMULT2, KMEMORY,KREMOTE,KDSWAP, KCOLL, KLOCKRD
C
C     SAVE ALL
C
C
C     ---------------------------------------

