      SUBROUTINE zritsc6 (IFLTAB, CPATH, JULS, ISTIME, JULE, IETIME,
     * LGETDOB, LFILDOB, ITIMES, SVALUES, DVALUES, KVALS, NVALS,
     * IBDATE, IQUAL, LQUAL, LQREAD, CUNITS, CTYPE, CSUPP,
     * ITZONE, CTZONE, COORDS, ICDESC, LCOORDS, INFLAG, ISTAT)
C
C
C
C
      INTEGER IFLTAB(*), IQUAL(*), ITIMES(*), ICDESC(*)
      REAL SVALUES(*)
      LOGICAL LQUAL, LQREAD, LGETDOB, LFILDOB, LCOORDS
C
      CHARACTER CPATH*(*), CUNITS*(*), CTYPE*(*)
	CHARACTER CTZONE*(*), CSUPP*(*)
C
      DOUBLE PRECISION DVALUES(*), COORDS(*)
C
      INCLUDE 'zdssts.h'
C
C
      CALL zritsi6 (IFLTAB, CPATH, JULS, ISTIME, JULE, IETIME,
     * LGETDOB, LFILDOB, ITIMES, SVALUES, DVALUES, KVALS, NVALS,
     * IBDATE, IQUAL, LQUAL, LQREAD, CUNITS, CTYPE, INTBUF,
     * NIBUFF, NUHEAD, COORDS, ICDESC, LCOORDS, INFLAG, ISTAT)
C
C
      IF ((ISTAT.LT.0).OR.(ISTAT.GE.9)) RETURN
C
      CTZONE = CRTZONE
      ITZONE = IRTZONE
C
      CSUPP = ' '
      KSUPP = LEN(CSUPP)
C
      IF (NUHEAD.GT.0) THEN
         NSUPP = NUHEAD * 4
	   NSUPP = MIN(NSUPP, KSUPP)
         CALL HOLCHR(INTBUF, 1, NSUPP, CSUPP, 1)
      ENDIF
C
      RETURN
C
      END

