      SUBROUTINE APLNB ( CLINE,IBEG,NL,CSEP,CAPP,NA,ISTAT )
C
C  APPEND <CAPP> TO <CLINE>.  <CSEP> IS AN OPTIONAL
C  SEPARATOR CHARACTER -- IF NOT USED, ITS VALUE SHOULD
C  BE 'NONE'.  <IBEG> IS THE POSITION IN <CLINE> FROM
C  WHICH TO APPEND <CAPP> --- HOWEVER, <CLINE> IS
C  STRIPPED OF BLANKS MOVING IN REVERSE ORDER FROM
C  <IBEG>.  <NL> AND <NA> ARE THE NOMINAL LENGTHS OF
C  <CLINE> AND <CAPP>, RESPECTIVELY.  <ISTAT> REFLECTS
C  THE FINAL STATUS OF THE REQUEST TO APPEND:
C     ISTAT    MEANING
C     -----    --------
C       0      SUCCESSFUL
C       1      NOT ENOUGH POSTIONS LEFT TO APPEND
C       2      <CAPP> IS ALL BLANK -- BLANKS CANNOT
C              BE APPENDED WITH THIS ROUTINE.
      CHARACTER*(*) CLINE,CSEP,CAPP
C
C     L=1
C     IF ( L.EQ.1 ) THEN
C     WRITE (3,*) 'IN APLNB ...'
C     WRITE (35,* ) 'CLINE=',CLINE
C     WRITE (35,* ) 'IBEG=',IBEG,'   NL=',NL,'  CSEP=',CSEP
C     WRITE (35,* ) 'CAPP=',CAPP,'   NA=',NA
C     WRITE ( 3,* )
C     ENDIF
      ISTAT = 0
      IF ( IBEG.LE.1 )  IBEG = 1
      IL1 = IBEG
   5  CONTINUE
      IF ( (IL1.GT.1).AND.CLINE(IL1-1:IL1-1).EQ.' ') THEN
         IL1 = IL1 - 1
         GO TO 5
      ENDIF
      IA2 = NA
  10  CONTINUE
      IF ( (IA2.GE.1).AND.CAPP(IA2:IA2).EQ.' ') THEN
         IA2 = IA2 - 1
         GO TO 10
      ENDIF
      IA1 = 1
  15  CONTINUE
      IF ( IA1.LT.IA2.AND.CAPP(IA1:IA1).EQ.' ') THEN
         IA1 = IA1 + 1
         GO TO 15
      ENDIF
      IF ( IA1.GT.IA2 ) THEN
         ISTAT = 2
         GO TO 90
      ENDIF
      IF ( CSEP.EQ.'NONE' ) THEN
         NS = 0
      ELSE
         NS = 1
      ENDIF
      IL2 = IL1 + NS + ( IA2 - IA1 + 1 ) - 1
      IF ( IL2.GT.NL ) THEN
         ISTAT = 1
         GO TO 90
      ENDIF
      IF ( NS.GT.0 ) THEN
         CLINE(IL1:IL1) = CSEP(1:1)
         IL1 = IL1 + 1
      ENDIF
      CLINE(IL1:IL2) = CAPP(IA1:IA2)
      IBEG = IL2 + 1
C       WRITE ( 35,* ) 'IA1=',IA1,'    IA2=',IA2
C       WRITE ( 35,* ) 'IBEG=',IBEG
   90 CONTINUE
      RETURN
      END
