C
C     FILE 2000SHEF*C.PSTBLS
C
C PARAMETER AND STATION TABLES
      PARAMETER ( MAXPAR=500)                                           H
c     PARAMETER ( MAXPAR=80)                                            M
      COMMON / PSTBLS / PE, PARAM, UNITS, TYPE,
     .  FACTOR, NSIG, IRND, NSTA,
     .  NPAR
      CHARACTER PE(MAXPAR)*3, PARAM(MAXPAR)*25
      CHARACTER UNITS(MAXPAR)*8, TYPE(MAXPAR)*8
      REAL FACTOR(MAXPAR)
      INTEGER NPAR, NSTA, NSIG(MAXPAR), IRND(MAXPAR)
C
C        PE      ---  SHEF PHYSICAL ELEMENT -- KEY TO PARAMETER TABLE
C                     ( INCLUDES EXTREMA CODE AS 3D CHARACTER )
C                     ( 3D CHARACTER IS EXTREMA CODE )
C        PARAM   ---  DSS PARAMETER NAME EQUIVALENT FOR PE
C        UNITS   ---  DSS UNITS EQUIVALENT FOR PE
C        TYPE    ---  DSS TIME-SERIES DATA TYPE FOR PE
C        FACTOR  ---  SCALE FACTOR APPLIED TO SHEF PE
C        NSIG    ---  NUMBER OF SIGNIFICANT DIGITS TO USE IN WRITING
C                     DATA VALUES
C        IRND    ---  POWER OF TEN TO ROUND TO IN WRITING DATA VALUES
C        NPAR    ---  NUMBER OF PARAMETERS DEFINED IN TABLE
C        NSTA    ---  NUMBER OF STATIONS   DEFINED IN TABLE
C        DSSID   ---  LABEL FOR DSS PATHNAME PART B  FOR STATION
C        SHEFID  ---  USED TO IDENTIFY STATION IN ACCORDANCE WITH SHEF
C
