C *****************************************************************************
C     CONTROL DATA
      COMMON /SDCNTL/ LFNOUT,IDEBUG,IADHOC,
     1  IDTZ,IOLVL,CFDEF,CIRBLK,CPSWD
      CHARACTER CFDEF*24,CIRBLK*10,CPSWD*8
C
C        LFNOUT  ---  OUTPUT FILE LFN
C        IDEBUG  ---  DEBUG SWITH 0=OFF 1=ON
C        IADHOC  ---  AD HOC SWITCH 0=OFF 1=ON
C                     IF ON, SENSOR NEED NOT BE IN LIST
C        CDSFIL  ---  DSS FILE NAME
C        CSFILE  ---  SENSOR FILE NAME
C        CPFILE  ---  PARAMETER FILE NAME
C        IDTZ    ---  DIFFERENCE FROM GMT IN HOURS
C        CFDEF   ---  DEFAULT DSS PATHNAME F-PART
C        CIRBLK  ---  DEFINES TIME BLOCK FOR IRREGULAR TS DATA
C        CPSWD   ---  USER PASSWORD FOR STATIONS WITH MATCHING PASSWORDS
C
