C *****************************************************************************
C     MISCELLANEOUS VARIABLES
c
      COMMON /SDMISC/ IfltabAddress, NTOTAL, NSETS,  
     * LDOALL, TSTYPE,ZPARAM, ZTYPE, ERRMSG, DES
C23456
      CHARACTER TSTYPE*2,ZPARAM*32,ZTYPE*8,ERRMSG*80,DES*24
      INTEGER IfltabAddress
	  LOGICAL LDOALL
C
C        IFLTAB  ---  FILE TABLE USED BY DSS ROUTINES
C        TSTYPE  ---  FLAG WHICH DISTINGUISHES BETWEEN REGULAR AND
C                     IRREGULAR TIME SERIES
C        ZTYPE   ---  THE DSS DATA TYPE USED AFTER ALL RELEVANT SHEF
C                     INFORMATION HAS BEEN CONSIDERED
C        ERRMSG  ---  CHARACTER BUFFER FOR ERROR MESSAGES FROM ROUTINES
C        DES     ---  DESCRIPTIVE QUALIFIER USED FOR F PART OF DSS PATH
C                     AND BASED ON THE SHEF TYPE AND SOURCE CODE
C