C     MONITOR COMMON SHFRAM                                             H
      COMMON/SHFRAM/PE(676),ID(26),IBTS(38),IBEX(2),PR(35),ISN(9,36)
      COMMON /CODES/ ICHA,ICHB,ICHC,ICHD,ICHE,ICHF,ICHG,ICHH,ICHI,
     1               ICHJ,ICHK,ICHL,ICHM,ICHN,ICHO,ICHP,ICHQ,ICHR,
     2               ICHS,ICHT,ICHU,ICHV,ICHW,ICHX,ICHY,ICHZ,ICH0,
     3               ICH1,ICH2,ICH3,ICH4,ICH5,ICH6,ICH7,ICH8,ICH9,
     4               IBLNK,ISLASH,ICOLON,IPLUS,IMINUS,IDOT,IARROW,
     5               ICOMMA
