      SUBROUTINE TASG( LFNOUT,LFN,CFILE )
C
C     TASG MAKES REPEATED ATTEMPTS TO MAKE A NORMAL ASSIGNMENT TO
C     A FILE.  THE ORIGINAL APPLICATION HERE IS FOR REFERENCE FILES
C     WHICH ARE QUICKLY ASSIGNED, READ, AND THEN RELEASED BY SEVERAL
C     "CONCURRENT" PROGRAMS.
C
      CHARACTER CFILE*(*)
C
      NWAIT = 0
    5 CONTINUE
      OPEN ( UNIT=LFN,FILE=CFILE,IOSTAT=IOS )         
         IF ( IOS.NE.0 ) THEN
            WRITE ( LFNOUT,* ) 'ERROR IN ASSIGNING STATION FILE'
            IF ( IOS.EQ.53 ) THEN
               WRITE ( LFNOUT,* ) 'FILE ACCESS DENIED'
            ELSE IF ( IOS.EQ.77 ) THEN
               WRITE ( LFNOUT,* ) 'OTHER USER WRITING TO FILE'
            ELSE
               WRITE ( LFNOUT,* ) 'SEE ERROR MESSAGE NO ',IOS+4500
            ENDIF
            RETURN
         ENDIF
      RETURN
      END
