      SUBROUTINE TOSHEF (LFNSHF, LFNOUT, CPATH, INTL,
     *  DATA, ITIME, NDATA, CUNITS)
C
C
      REAL DATA(NDATA)
      INTEGER ITIME(NDATA), LFNOUT, LFNSHF
      CHARACTER CPATH*(*), CUNITS*(*)
C
      CHARACTER TZONE*3, PCTS*2
      LOGICAL REPLCE
C
      DATA NSIG0/8/,IRND0/-10/,PCTS/' '/
C
	TZONE = 'Z'      
      REPLCE = .FALSE.
C
      CALL PUTSHF( LFNOUT,LFNSHF,CPATH,
     1  DATA,NDATA,ITIME,INTL,
     2  TZONE,NSIG0,IRND0,PCTS,REPLCE,CUNITS)
C
      RETURN  
      END

