#  Dss-C 
CFLAGS=-m64 -c -fPIC -g -std=gnu99 -I../../heclib/headers -I. -Werror=implicit-function-declaration --pipe  -D__linux__

csrc = $(wildcard source/*.c) \
       $(wildcard *.c) 

obj = $(csrc:.c=.o)

LDFLAGS = -lz -lrt -lgfortran -lm


all:Dss-C
	(cd ../../heclib; make -f Makefile.Linux)

clean:
	$(RM) source/*.o *.o ./Output/Dss-C

test:Dss-C
	(cd ../../heclib; make -f Makefile.Linux)
	mkdir -p Output
	rm -f Output/*.dss
	cp ../../dss-test-data/*.dss ./Output/
	(cd Output; ./Dss-C test)


Dss-C: $(obj)
	$(CC) -o Output/$@ $^ ../../heclib/Output/heclib.a $(LDFLAGS)