#
#  Dss-C testing makefile
#

CFLAGS=-m64 -c -I../../heclib/headers -I. -mt -xcode=pic32 -xstrconst -xc99=all -xCC -g -xs 

all:Dss-C
	(cd ../../heclib; make -f Makefile.Solaris)

clean:
	$(RM) Output/*.o

test:Dss-C
	(cd ../../heclib; make -f Makefile.Solaris)
	mkdir -p Output
	rm -f Output/*.dss
	cp ../../dss-test-data/*.dss ./Output/
	(cd Output; ./Dss-C test)


Output/%.o:source/%.c
	$(CC) $(CFLAGS) $^ -o $@
Output/%.o:%.c
	$(CC) $(CFLAGS) $^ -o  $@

OBJS:sh=find ./source | grep \\.c$ | sed 's/\.c$/.o/' | sed 's/source/Output/'
OBJS2:sh=ls ./*.c | sed 's/\.c$/.o/' | sed 's/\.\//Output\//'

Dss-C:$(OBJS) $(OBJS2)
	echo $(OBJS) $(OBJS2)
	f95 -mt -m64 -xcode=pic32 -xpagesize=4M Output/*.o ../../heclib/Output/heclib.a -o Output/Dss-C -lrt -lz -g -xs
