#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <normalizeFPart.h>
#include <heclib.h>

typedef struct normalize_f_part_test_s {
	char* fPart;
	int   expected_status;
	char* expected_normalized;
} normalize_f_part_test;

int test_normalize_f_part() {
	normalize_f_part_test tests[] = {
		//-----------------------------------------//
		// Errors that indicate non-tagged F parts //
		//-----------------------------------------//
		{"normal_f_part",    normalizeFPartStatus.NO_TAG_SEPARATOR,        NULL}, // Test  1 : normal F part with no tag
		{"normal|f_part",    normalizeFPartStatus.NO_TAG_SEPARATOR,        NULL}, // Test  2 : normal F part with no tag
		{"normal:f_part",    normalizeFPartStatus.INVALID_TAG_FORMAT,      NULL}, // Test  3 : normal F part with no tag
		{"c:normal|f_part|", normalizeFPartStatus.MULTIPLE_UNTAGGED_PARTS, NULL}, // Test  4 : normal F part with no tag (would parse as tagged F part without second pipe char)
		{"",                 normalizeFPartStatus.EMPTY_F_PART,            NULL}, // Test  5 : empty F Part
		//---------------------------------------------------//
		// Errors that indicate F parts with invalid tagging //
		//---------------------------------------------------//
		{"C:000001|F:20220228-1200|V:20220228-143000|N:ResSim Only|R:----E0|User String",   normalizeFPartStatus.INVALID_TAG_CHARACTER,  NULL}, // Test  6 : Invalid tag character
		{"C:000001|T:20220228-1200|T:20220228-143000|N:ResSim Only|R:----E0|User String",   normalizeFPartStatus.REPEATED_TAG_CHARACTER, NULL}, // Test  7 : Duplicate tag character
		{"C:0000001|T:20220228-1200|V:20220228-143000|N:ResSim Only|R:----E0|User String",  normalizeFPartStatus.INVALID_C_TAG_VALUE,    NULL}, // Test  8 : Collection value too long
		{"C:000001|T:20220228-120000|V:20220228-143000|N:ResSim Only|R:----E0|User String", normalizeFPartStatus.INVALID_T_TAG_VALUE,    NULL}, // Test  9 : Time of forecast includes seconds
		{"C:000001|T:20220229-1200|V:20220228-143000|N:ResSim Only|R:----E0|User String",   normalizeFPartStatus.INVALID_T_TAG_VALUE,    NULL}, // Test 10 : Time of forecast includes invalid date
		{"C:000001|T:20220228-1200|V:20220228-1430|N:ResSim Only|R:----E0|User String",     normalizeFPartStatus.INVALID_V_TAG_VALUE,    NULL}, // Test 11 : Version time doesn't include seconds
		{"C:000001|T:20220228-1200|V:20220228-243000|N:ResSim Only|R:----E0|User String",   normalizeFPartStatus.INVALID_V_TAG_VALUE,    NULL}, // Test 12 : Version time includes invalid time
		{"C:000001|T:20220228-1200|V:20220228-143000|N:ResSim Only|R:---E0|User String",    normalizeFPartStatus.INVALID_R_TAG_VALUE,    NULL}, // Test 13 : Run string has odd number of characters
		{"C:000001|T:20220228-1200|V:20220228-143000|N:ResSim Only|R:----@0|User String",   normalizeFPartStatus.INVALID_R_TAG_VALUE,    NULL}, // Test 14 : Run model alternative is not alphanumeric
		{"C:000001|T:20220228-1200|V:20220228-143000|N:ResSim Only|R:----EX|User String",   normalizeFPartStatus.INVALID_R_TAG_VALUE,    NULL}, // Test 15 : Run model trial number is not numeric
		//----------------------------------------------------------------------------------------//
		// All following tests were generated by the python script at the end of this source file //
		//----------------------------------------------------------------------------------------//
		//--------------------------//
		// 5 tags taken 5 at a time //
		//--------------------------//
		{"c:000001|n:ResSim Only|t:20220228-1200|r:----E0|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 16 : C,N,T,R,V
		{"c:000001|n:ResSim Only|t:20220228-1200|v:20200229-143000|r:----E0|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 17 : C,N,T,R,V
		{"c:000001|n:ResSim Only|r:----E0|t:20220228-1200|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 18 : C,N,T,R,V
		{"c:000001|n:ResSim Only|r:----E0|v:20200229-143000|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 19 : C,N,T,R,V
		{"c:000001|n:ResSim Only|v:20200229-143000|t:20220228-1200|r:----E0|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 20 : C,N,T,R,V
		{"c:000001|n:ResSim Only|v:20200229-143000|r:----E0|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 21 : C,N,T,R,V
		{"c:000001|t:20220228-1200|n:ResSim Only|r:----E0|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 22 : C,N,T,R,V
		{"c:000001|t:20220228-1200|n:ResSim Only|v:20200229-143000|r:----E0|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 23 : C,N,T,R,V
		{"c:000001|t:20220228-1200|r:----E0|n:ResSim Only|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 24 : C,N,T,R,V
		{"c:000001|t:20220228-1200|r:----E0|v:20200229-143000|n:ResSim Only|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 25 : C,N,T,R,V
		{"c:000001|t:20220228-1200|v:20200229-143000|n:ResSim Only|r:----E0|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 26 : C,N,T,R,V
		{"c:000001|t:20220228-1200|v:20200229-143000|r:----E0|n:ResSim Only|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 27 : C,N,T,R,V
		{"c:000001|r:----E0|n:ResSim Only|t:20220228-1200|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 28 : C,N,T,R,V
		{"c:000001|r:----E0|n:ResSim Only|v:20200229-143000|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 29 : C,N,T,R,V
		{"c:000001|r:----E0|t:20220228-1200|n:ResSim Only|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 30 : C,N,T,R,V
		{"c:000001|r:----E0|t:20220228-1200|v:20200229-143000|n:ResSim Only|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 31 : C,N,T,R,V
		{"c:000001|r:----E0|v:20200229-143000|n:ResSim Only|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 32 : C,N,T,R,V
		{"c:000001|r:----E0|v:20200229-143000|t:20220228-1200|n:ResSim Only|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 33 : C,N,T,R,V
		{"c:000001|v:20200229-143000|n:ResSim Only|t:20220228-1200|r:----E0|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 34 : C,N,T,R,V
		{"c:000001|v:20200229-143000|n:ResSim Only|r:----E0|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 35 : C,N,T,R,V
		{"c:000001|v:20200229-143000|t:20220228-1200|n:ResSim Only|r:----E0|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 36 : C,N,T,R,V
		{"c:000001|v:20200229-143000|t:20220228-1200|r:----E0|n:ResSim Only|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 37 : C,N,T,R,V
		{"c:000001|v:20200229-143000|r:----E0|n:ResSim Only|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 38 : C,N,T,R,V
		{"c:000001|v:20200229-143000|r:----E0|t:20220228-1200|n:ResSim Only|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 39 : C,N,T,R,V
		{"n:ResSim Only|c:000001|t:20220228-1200|r:----E0|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 40 : C,N,T,R,V
		{"n:ResSim Only|c:000001|t:20220228-1200|v:20200229-143000|r:----E0|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 41 : C,N,T,R,V
		{"n:ResSim Only|c:000001|r:----E0|t:20220228-1200|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 42 : C,N,T,R,V
		{"n:ResSim Only|c:000001|r:----E0|v:20200229-143000|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 43 : C,N,T,R,V
		{"n:ResSim Only|c:000001|v:20200229-143000|t:20220228-1200|r:----E0|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 44 : C,N,T,R,V
		{"n:ResSim Only|c:000001|v:20200229-143000|r:----E0|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 45 : C,N,T,R,V
		{"n:ResSim Only|t:20220228-1200|c:000001|r:----E0|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 46 : C,N,T,R,V
		{"n:ResSim Only|t:20220228-1200|c:000001|v:20200229-143000|r:----E0|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 47 : C,N,T,R,V
		{"n:ResSim Only|t:20220228-1200|r:----E0|c:000001|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 48 : C,N,T,R,V
		{"n:ResSim Only|t:20220228-1200|r:----E0|v:20200229-143000|c:000001|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 49 : C,N,T,R,V
		{"n:ResSim Only|t:20220228-1200|v:20200229-143000|c:000001|r:----E0|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 50 : C,N,T,R,V
		{"n:ResSim Only|t:20220228-1200|v:20200229-143000|r:----E0|c:000001|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 51 : C,N,T,R,V
		{"n:ResSim Only|r:----E0|c:000001|t:20220228-1200|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 52 : C,N,T,R,V
		{"n:ResSim Only|r:----E0|c:000001|v:20200229-143000|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 53 : C,N,T,R,V
		{"n:ResSim Only|r:----E0|t:20220228-1200|c:000001|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 54 : C,N,T,R,V
		{"n:ResSim Only|r:----E0|t:20220228-1200|v:20200229-143000|c:000001|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 55 : C,N,T,R,V
		{"n:ResSim Only|r:----E0|v:20200229-143000|c:000001|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 56 : C,N,T,R,V
		{"n:ResSim Only|r:----E0|v:20200229-143000|t:20220228-1200|c:000001|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 57 : C,N,T,R,V
		{"n:ResSim Only|v:20200229-143000|c:000001|t:20220228-1200|r:----E0|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 58 : C,N,T,R,V
		{"n:ResSim Only|v:20200229-143000|c:000001|r:----E0|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 59 : C,N,T,R,V
		{"n:ResSim Only|v:20200229-143000|t:20220228-1200|c:000001|r:----E0|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 60 : C,N,T,R,V
		{"n:ResSim Only|v:20200229-143000|t:20220228-1200|r:----E0|c:000001|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 61 : C,N,T,R,V
		{"n:ResSim Only|v:20200229-143000|r:----E0|c:000001|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 62 : C,N,T,R,V
		{"n:ResSim Only|v:20200229-143000|r:----E0|t:20220228-1200|c:000001|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 63 : C,N,T,R,V
		{"t:20220228-1200|c:000001|n:ResSim Only|r:----E0|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 64 : C,N,T,R,V
		{"t:20220228-1200|c:000001|n:ResSim Only|v:20200229-143000|r:----E0|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 65 : C,N,T,R,V
		{"t:20220228-1200|c:000001|r:----E0|n:ResSim Only|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 66 : C,N,T,R,V
		{"t:20220228-1200|c:000001|r:----E0|v:20200229-143000|n:ResSim Only|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 67 : C,N,T,R,V
		{"t:20220228-1200|c:000001|v:20200229-143000|n:ResSim Only|r:----E0|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 68 : C,N,T,R,V
		{"t:20220228-1200|c:000001|v:20200229-143000|r:----E0|n:ResSim Only|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 69 : C,N,T,R,V
		{"t:20220228-1200|n:ResSim Only|c:000001|r:----E0|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 70 : C,N,T,R,V
		{"t:20220228-1200|n:ResSim Only|c:000001|v:20200229-143000|r:----E0|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 71 : C,N,T,R,V
		{"t:20220228-1200|n:ResSim Only|r:----E0|c:000001|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 72 : C,N,T,R,V
		{"t:20220228-1200|n:ResSim Only|r:----E0|v:20200229-143000|c:000001|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 73 : C,N,T,R,V
		{"t:20220228-1200|n:ResSim Only|v:20200229-143000|c:000001|r:----E0|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 74 : C,N,T,R,V
		{"t:20220228-1200|n:ResSim Only|v:20200229-143000|r:----E0|c:000001|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 75 : C,N,T,R,V
		{"t:20220228-1200|r:----E0|c:000001|n:ResSim Only|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 76 : C,N,T,R,V
		{"t:20220228-1200|r:----E0|c:000001|v:20200229-143000|n:ResSim Only|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 77 : C,N,T,R,V
		{"t:20220228-1200|r:----E0|n:ResSim Only|c:000001|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 78 : C,N,T,R,V
		{"t:20220228-1200|r:----E0|n:ResSim Only|v:20200229-143000|c:000001|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 79 : C,N,T,R,V
		{"t:20220228-1200|r:----E0|v:20200229-143000|c:000001|n:ResSim Only|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 80 : C,N,T,R,V
		{"t:20220228-1200|r:----E0|v:20200229-143000|n:ResSim Only|c:000001|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 81 : C,N,T,R,V
		{"t:20220228-1200|v:20200229-143000|c:000001|n:ResSim Only|r:----E0|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 82 : C,N,T,R,V
		{"t:20220228-1200|v:20200229-143000|c:000001|r:----E0|n:ResSim Only|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 83 : C,N,T,R,V
		{"t:20220228-1200|v:20200229-143000|n:ResSim Only|c:000001|r:----E0|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 84 : C,N,T,R,V
		{"t:20220228-1200|v:20200229-143000|n:ResSim Only|r:----E0|c:000001|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 85 : C,N,T,R,V
		{"t:20220228-1200|v:20200229-143000|r:----E0|c:000001|n:ResSim Only|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 86 : C,N,T,R,V
		{"t:20220228-1200|v:20200229-143000|r:----E0|n:ResSim Only|c:000001|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 87 : C,N,T,R,V
		{"r:----E0|c:000001|n:ResSim Only|t:20220228-1200|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 88 : C,N,T,R,V
		{"r:----E0|c:000001|n:ResSim Only|v:20200229-143000|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 89 : C,N,T,R,V
		{"r:----E0|c:000001|t:20220228-1200|n:ResSim Only|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 90 : C,N,T,R,V
		{"r:----E0|c:000001|t:20220228-1200|v:20200229-143000|n:ResSim Only|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 91 : C,N,T,R,V
		{"r:----E0|c:000001|v:20200229-143000|n:ResSim Only|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 92 : C,N,T,R,V
		{"r:----E0|c:000001|v:20200229-143000|t:20220228-1200|n:ResSim Only|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 93 : C,N,T,R,V
		{"r:----E0|n:ResSim Only|c:000001|t:20220228-1200|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 94 : C,N,T,R,V
		{"r:----E0|n:ResSim Only|c:000001|v:20200229-143000|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 95 : C,N,T,R,V
		{"r:----E0|n:ResSim Only|t:20220228-1200|c:000001|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 96 : C,N,T,R,V
		{"r:----E0|n:ResSim Only|t:20220228-1200|v:20200229-143000|c:000001|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 97 : C,N,T,R,V
		{"r:----E0|n:ResSim Only|v:20200229-143000|c:000001|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 98 : C,N,T,R,V
		{"r:----E0|n:ResSim Only|v:20200229-143000|t:20220228-1200|c:000001|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 99 : C,N,T,R,V
		{"r:----E0|t:20220228-1200|c:000001|n:ResSim Only|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 100 : C,N,T,R,V
		{"r:----E0|t:20220228-1200|c:000001|v:20200229-143000|n:ResSim Only|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 101 : C,N,T,R,V
		{"r:----E0|t:20220228-1200|n:ResSim Only|c:000001|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 102 : C,N,T,R,V
		{"r:----E0|t:20220228-1200|n:ResSim Only|v:20200229-143000|c:000001|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 103 : C,N,T,R,V
		{"r:----E0|t:20220228-1200|v:20200229-143000|c:000001|n:ResSim Only|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 104 : C,N,T,R,V
		{"r:----E0|t:20220228-1200|v:20200229-143000|n:ResSim Only|c:000001|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 105 : C,N,T,R,V
		{"r:----E0|v:20200229-143000|c:000001|n:ResSim Only|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 106 : C,N,T,R,V
		{"r:----E0|v:20200229-143000|c:000001|t:20220228-1200|n:ResSim Only|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 107 : C,N,T,R,V
		{"r:----E0|v:20200229-143000|n:ResSim Only|c:000001|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 108 : C,N,T,R,V
		{"r:----E0|v:20200229-143000|n:ResSim Only|t:20220228-1200|c:000001|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 109 : C,N,T,R,V
		{"r:----E0|v:20200229-143000|t:20220228-1200|c:000001|n:ResSim Only|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 110 : C,N,T,R,V
		{"r:----E0|v:20200229-143000|t:20220228-1200|n:ResSim Only|c:000001|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 111 : C,N,T,R,V
		{"v:20200229-143000|c:000001|n:ResSim Only|t:20220228-1200|r:----E0|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 112 : C,N,T,R,V
		{"v:20200229-143000|c:000001|n:ResSim Only|r:----E0|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 113 : C,N,T,R,V
		{"v:20200229-143000|c:000001|t:20220228-1200|n:ResSim Only|r:----E0|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 114 : C,N,T,R,V
		{"v:20200229-143000|c:000001|t:20220228-1200|r:----E0|n:ResSim Only|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 115 : C,N,T,R,V
		{"v:20200229-143000|c:000001|r:----E0|n:ResSim Only|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 116 : C,N,T,R,V
		{"v:20200229-143000|c:000001|r:----E0|t:20220228-1200|n:ResSim Only|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 117 : C,N,T,R,V
		{"v:20200229-143000|n:ResSim Only|c:000001|t:20220228-1200|r:----E0|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 118 : C,N,T,R,V
		{"v:20200229-143000|n:ResSim Only|c:000001|r:----E0|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 119 : C,N,T,R,V
		{"v:20200229-143000|n:ResSim Only|t:20220228-1200|c:000001|r:----E0|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 120 : C,N,T,R,V
		{"v:20200229-143000|n:ResSim Only|t:20220228-1200|r:----E0|c:000001|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 121 : C,N,T,R,V
		{"v:20200229-143000|n:ResSim Only|r:----E0|c:000001|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 122 : C,N,T,R,V
		{"v:20200229-143000|n:ResSim Only|r:----E0|t:20220228-1200|c:000001|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 123 : C,N,T,R,V
		{"v:20200229-143000|t:20220228-1200|c:000001|n:ResSim Only|r:----E0|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 124 : C,N,T,R,V
		{"v:20200229-143000|t:20220228-1200|c:000001|r:----E0|n:ResSim Only|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 125 : C,N,T,R,V
		{"v:20200229-143000|t:20220228-1200|n:ResSim Only|c:000001|r:----E0|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 126 : C,N,T,R,V
		{"v:20200229-143000|t:20220228-1200|n:ResSim Only|r:----E0|c:000001|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 127 : C,N,T,R,V
		{"v:20200229-143000|t:20220228-1200|r:----E0|c:000001|n:ResSim Only|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 128 : C,N,T,R,V
		{"v:20200229-143000|t:20220228-1200|r:----E0|n:ResSim Only|c:000001|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 129 : C,N,T,R,V
		{"v:20200229-143000|r:----E0|c:000001|n:ResSim Only|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 130 : C,N,T,R,V
		{"v:20200229-143000|r:----E0|c:000001|t:20220228-1200|n:ResSim Only|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 131 : C,N,T,R,V
		{"v:20200229-143000|r:----E0|n:ResSim Only|c:000001|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 132 : C,N,T,R,V
		{"v:20200229-143000|r:----E0|n:ResSim Only|t:20220228-1200|c:000001|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 133 : C,N,T,R,V
		{"v:20200229-143000|r:----E0|t:20220228-1200|c:000001|n:ResSim Only|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 134 : C,N,T,R,V
		{"v:20200229-143000|r:----E0|t:20220228-1200|n:ResSim Only|c:000001|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 135 : C,N,T,R,V
		//--------------------------//
		// 5 tags taken 4 at a time //
		//--------------------------//
		{"c:000001|n:ResSim Only|t:20220228-1200|r:----E0|User String",          normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|User String"         }, // test 136 : C,N,T,R
		{"c:000001|n:ResSim Only|r:----E0|t:20220228-1200|User String",          normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|User String"         }, // test 137 : C,N,T,R
		{"c:000001|t:20220228-1200|n:ResSim Only|r:----E0|User String",          normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|User String"         }, // test 138 : C,N,T,R
		{"c:000001|t:20220228-1200|r:----E0|n:ResSim Only|User String",          normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|User String"         }, // test 139 : C,N,T,R
		{"c:000001|r:----E0|n:ResSim Only|t:20220228-1200|User String",          normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|User String"         }, // test 140 : C,N,T,R
		{"c:000001|r:----E0|t:20220228-1200|n:ResSim Only|User String",          normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|User String"         }, // test 141 : C,N,T,R
		{"n:ResSim Only|c:000001|t:20220228-1200|r:----E0|User String",          normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|User String"         }, // test 142 : C,N,T,R
		{"n:ResSim Only|c:000001|r:----E0|t:20220228-1200|User String",          normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|User String"         }, // test 143 : C,N,T,R
		{"n:ResSim Only|t:20220228-1200|c:000001|r:----E0|User String",          normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|User String"         }, // test 144 : C,N,T,R
		{"n:ResSim Only|t:20220228-1200|r:----E0|c:000001|User String",          normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|User String"         }, // test 145 : C,N,T,R
		{"n:ResSim Only|r:----E0|c:000001|t:20220228-1200|User String",          normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|User String"         }, // test 146 : C,N,T,R
		{"n:ResSim Only|r:----E0|t:20220228-1200|c:000001|User String",          normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|User String"         }, // test 147 : C,N,T,R
		{"t:20220228-1200|c:000001|n:ResSim Only|r:----E0|User String",          normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|User String"         }, // test 148 : C,N,T,R
		{"t:20220228-1200|c:000001|r:----E0|n:ResSim Only|User String",          normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|User String"         }, // test 149 : C,N,T,R
		{"t:20220228-1200|n:ResSim Only|c:000001|r:----E0|User String",          normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|User String"         }, // test 150 : C,N,T,R
		{"t:20220228-1200|n:ResSim Only|r:----E0|c:000001|User String",          normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|User String"         }, // test 151 : C,N,T,R
		{"t:20220228-1200|r:----E0|c:000001|n:ResSim Only|User String",          normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|User String"         }, // test 152 : C,N,T,R
		{"t:20220228-1200|r:----E0|n:ResSim Only|c:000001|User String",          normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|User String"         }, // test 153 : C,N,T,R
		{"r:----E0|c:000001|n:ResSim Only|t:20220228-1200|User String",          normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|User String"         }, // test 154 : C,N,T,R
		{"r:----E0|c:000001|t:20220228-1200|n:ResSim Only|User String",          normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|User String"         }, // test 155 : C,N,T,R
		{"r:----E0|n:ResSim Only|c:000001|t:20220228-1200|User String",          normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|User String"         }, // test 156 : C,N,T,R
		{"r:----E0|n:ResSim Only|t:20220228-1200|c:000001|User String",          normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|User String"         }, // test 157 : C,N,T,R
		{"r:----E0|t:20220228-1200|c:000001|n:ResSim Only|User String",          normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|User String"         }, // test 158 : C,N,T,R
		{"r:----E0|t:20220228-1200|n:ResSim Only|c:000001|User String",          normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|R:----E0|User String"         }, // test 159 : C,N,T,R
		{"c:000001|n:ResSim Only|t:20220228-1200|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|V:20200229-143000|User String"}, // test 160 : C,N,T,V
		{"c:000001|n:ResSim Only|v:20200229-143000|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|V:20200229-143000|User String"}, // test 161 : C,N,T,V
		{"c:000001|t:20220228-1200|n:ResSim Only|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|V:20200229-143000|User String"}, // test 162 : C,N,T,V
		{"c:000001|t:20220228-1200|v:20200229-143000|n:ResSim Only|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|V:20200229-143000|User String"}, // test 163 : C,N,T,V
		{"c:000001|v:20200229-143000|n:ResSim Only|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|V:20200229-143000|User String"}, // test 164 : C,N,T,V
		{"c:000001|v:20200229-143000|t:20220228-1200|n:ResSim Only|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|V:20200229-143000|User String"}, // test 165 : C,N,T,V
		{"n:ResSim Only|c:000001|t:20220228-1200|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|V:20200229-143000|User String"}, // test 166 : C,N,T,V
		{"n:ResSim Only|c:000001|v:20200229-143000|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|V:20200229-143000|User String"}, // test 167 : C,N,T,V
		{"n:ResSim Only|t:20220228-1200|c:000001|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|V:20200229-143000|User String"}, // test 168 : C,N,T,V
		{"n:ResSim Only|t:20220228-1200|v:20200229-143000|c:000001|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|V:20200229-143000|User String"}, // test 169 : C,N,T,V
		{"n:ResSim Only|v:20200229-143000|c:000001|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|V:20200229-143000|User String"}, // test 170 : C,N,T,V
		{"n:ResSim Only|v:20200229-143000|t:20220228-1200|c:000001|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|V:20200229-143000|User String"}, // test 171 : C,N,T,V
		{"t:20220228-1200|c:000001|n:ResSim Only|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|V:20200229-143000|User String"}, // test 172 : C,N,T,V
		{"t:20220228-1200|c:000001|v:20200229-143000|n:ResSim Only|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|V:20200229-143000|User String"}, // test 173 : C,N,T,V
		{"t:20220228-1200|n:ResSim Only|c:000001|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|V:20200229-143000|User String"}, // test 174 : C,N,T,V
		{"t:20220228-1200|n:ResSim Only|v:20200229-143000|c:000001|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|V:20200229-143000|User String"}, // test 175 : C,N,T,V
		{"t:20220228-1200|v:20200229-143000|c:000001|n:ResSim Only|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|V:20200229-143000|User String"}, // test 176 : C,N,T,V
		{"t:20220228-1200|v:20200229-143000|n:ResSim Only|c:000001|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|V:20200229-143000|User String"}, // test 177 : C,N,T,V
		{"v:20200229-143000|c:000001|n:ResSim Only|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|V:20200229-143000|User String"}, // test 178 : C,N,T,V
		{"v:20200229-143000|c:000001|t:20220228-1200|n:ResSim Only|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|V:20200229-143000|User String"}, // test 179 : C,N,T,V
		{"v:20200229-143000|n:ResSim Only|c:000001|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|V:20200229-143000|User String"}, // test 180 : C,N,T,V
		{"v:20200229-143000|n:ResSim Only|t:20220228-1200|c:000001|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|V:20200229-143000|User String"}, // test 181 : C,N,T,V
		{"v:20200229-143000|t:20220228-1200|c:000001|n:ResSim Only|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|V:20200229-143000|User String"}, // test 182 : C,N,T,V
		{"v:20200229-143000|t:20220228-1200|n:ResSim Only|c:000001|User String", normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|V:20200229-143000|User String"}, // test 183 : C,N,T,V
		{"c:000001|n:ResSim Only|r:----E0|v:20200229-143000|User String",        normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|R:----E0|V:20200229-143000|User String"       }, // test 184 : C,N,R,V
		{"c:000001|n:ResSim Only|v:20200229-143000|r:----E0|User String",        normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|R:----E0|V:20200229-143000|User String"       }, // test 185 : C,N,R,V
		{"c:000001|r:----E0|n:ResSim Only|v:20200229-143000|User String",        normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|R:----E0|V:20200229-143000|User String"       }, // test 186 : C,N,R,V
		{"c:000001|r:----E0|v:20200229-143000|n:ResSim Only|User String",        normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|R:----E0|V:20200229-143000|User String"       }, // test 187 : C,N,R,V
		{"c:000001|v:20200229-143000|n:ResSim Only|r:----E0|User String",        normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|R:----E0|V:20200229-143000|User String"       }, // test 188 : C,N,R,V
		{"c:000001|v:20200229-143000|r:----E0|n:ResSim Only|User String",        normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|R:----E0|V:20200229-143000|User String"       }, // test 189 : C,N,R,V
		{"n:ResSim Only|c:000001|r:----E0|v:20200229-143000|User String",        normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|R:----E0|V:20200229-143000|User String"       }, // test 190 : C,N,R,V
		{"n:ResSim Only|c:000001|v:20200229-143000|r:----E0|User String",        normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|R:----E0|V:20200229-143000|User String"       }, // test 191 : C,N,R,V
		{"n:ResSim Only|r:----E0|c:000001|v:20200229-143000|User String",        normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|R:----E0|V:20200229-143000|User String"       }, // test 192 : C,N,R,V
		{"n:ResSim Only|r:----E0|v:20200229-143000|c:000001|User String",        normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|R:----E0|V:20200229-143000|User String"       }, // test 193 : C,N,R,V
		{"n:ResSim Only|v:20200229-143000|c:000001|r:----E0|User String",        normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|R:----E0|V:20200229-143000|User String"       }, // test 194 : C,N,R,V
		{"n:ResSim Only|v:20200229-143000|r:----E0|c:000001|User String",        normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|R:----E0|V:20200229-143000|User String"       }, // test 195 : C,N,R,V
		{"r:----E0|c:000001|n:ResSim Only|v:20200229-143000|User String",        normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|R:----E0|V:20200229-143000|User String"       }, // test 196 : C,N,R,V
		{"r:----E0|c:000001|v:20200229-143000|n:ResSim Only|User String",        normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|R:----E0|V:20200229-143000|User String"       }, // test 197 : C,N,R,V
		{"r:----E0|n:ResSim Only|c:000001|v:20200229-143000|User String",        normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|R:----E0|V:20200229-143000|User String"       }, // test 198 : C,N,R,V
		{"r:----E0|n:ResSim Only|v:20200229-143000|c:000001|User String",        normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|R:----E0|V:20200229-143000|User String"       }, // test 199 : C,N,R,V
		{"r:----E0|v:20200229-143000|c:000001|n:ResSim Only|User String",        normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|R:----E0|V:20200229-143000|User String"       }, // test 200 : C,N,R,V
		{"r:----E0|v:20200229-143000|n:ResSim Only|c:000001|User String",        normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|R:----E0|V:20200229-143000|User String"       }, // test 201 : C,N,R,V
		{"v:20200229-143000|c:000001|n:ResSim Only|r:----E0|User String",        normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|R:----E0|V:20200229-143000|User String"       }, // test 202 : C,N,R,V
		{"v:20200229-143000|c:000001|r:----E0|n:ResSim Only|User String",        normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|R:----E0|V:20200229-143000|User String"       }, // test 203 : C,N,R,V
		{"v:20200229-143000|n:ResSim Only|c:000001|r:----E0|User String",        normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|R:----E0|V:20200229-143000|User String"       }, // test 204 : C,N,R,V
		{"v:20200229-143000|n:ResSim Only|r:----E0|c:000001|User String",        normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|R:----E0|V:20200229-143000|User String"       }, // test 205 : C,N,R,V
		{"v:20200229-143000|r:----E0|c:000001|n:ResSim Only|User String",        normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|R:----E0|V:20200229-143000|User String"       }, // test 206 : C,N,R,V
		{"v:20200229-143000|r:----E0|n:ResSim Only|c:000001|User String",        normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|R:----E0|V:20200229-143000|User String"       }, // test 207 : C,N,R,V
		{"c:000001|t:20220228-1200|r:----E0|v:20200229-143000|User String",      normalizeFPartStatus.SUCCESS, "C:000001|T:20220228-1200|R:----E0|V:20200229-143000|User String"     }, // test 208 : C,T,R,V
		{"c:000001|t:20220228-1200|v:20200229-143000|r:----E0|User String",      normalizeFPartStatus.SUCCESS, "C:000001|T:20220228-1200|R:----E0|V:20200229-143000|User String"     }, // test 209 : C,T,R,V
		{"c:000001|r:----E0|t:20220228-1200|v:20200229-143000|User String",      normalizeFPartStatus.SUCCESS, "C:000001|T:20220228-1200|R:----E0|V:20200229-143000|User String"     }, // test 210 : C,T,R,V
		{"c:000001|r:----E0|v:20200229-143000|t:20220228-1200|User String",      normalizeFPartStatus.SUCCESS, "C:000001|T:20220228-1200|R:----E0|V:20200229-143000|User String"     }, // test 211 : C,T,R,V
		{"c:000001|v:20200229-143000|t:20220228-1200|r:----E0|User String",      normalizeFPartStatus.SUCCESS, "C:000001|T:20220228-1200|R:----E0|V:20200229-143000|User String"     }, // test 212 : C,T,R,V
		{"c:000001|v:20200229-143000|r:----E0|t:20220228-1200|User String",      normalizeFPartStatus.SUCCESS, "C:000001|T:20220228-1200|R:----E0|V:20200229-143000|User String"     }, // test 213 : C,T,R,V
		{"t:20220228-1200|c:000001|r:----E0|v:20200229-143000|User String",      normalizeFPartStatus.SUCCESS, "C:000001|T:20220228-1200|R:----E0|V:20200229-143000|User String"     }, // test 214 : C,T,R,V
		{"t:20220228-1200|c:000001|v:20200229-143000|r:----E0|User String",      normalizeFPartStatus.SUCCESS, "C:000001|T:20220228-1200|R:----E0|V:20200229-143000|User String"     }, // test 215 : C,T,R,V
		{"t:20220228-1200|r:----E0|c:000001|v:20200229-143000|User String",      normalizeFPartStatus.SUCCESS, "C:000001|T:20220228-1200|R:----E0|V:20200229-143000|User String"     }, // test 216 : C,T,R,V
		{"t:20220228-1200|r:----E0|v:20200229-143000|c:000001|User String",      normalizeFPartStatus.SUCCESS, "C:000001|T:20220228-1200|R:----E0|V:20200229-143000|User String"     }, // test 217 : C,T,R,V
		{"t:20220228-1200|v:20200229-143000|c:000001|r:----E0|User String",      normalizeFPartStatus.SUCCESS, "C:000001|T:20220228-1200|R:----E0|V:20200229-143000|User String"     }, // test 218 : C,T,R,V
		{"t:20220228-1200|v:20200229-143000|r:----E0|c:000001|User String",      normalizeFPartStatus.SUCCESS, "C:000001|T:20220228-1200|R:----E0|V:20200229-143000|User String"     }, // test 219 : C,T,R,V
		{"r:----E0|c:000001|t:20220228-1200|v:20200229-143000|User String",      normalizeFPartStatus.SUCCESS, "C:000001|T:20220228-1200|R:----E0|V:20200229-143000|User String"     }, // test 220 : C,T,R,V
		{"r:----E0|c:000001|v:20200229-143000|t:20220228-1200|User String",      normalizeFPartStatus.SUCCESS, "C:000001|T:20220228-1200|R:----E0|V:20200229-143000|User String"     }, // test 221 : C,T,R,V
		{"r:----E0|t:20220228-1200|c:000001|v:20200229-143000|User String",      normalizeFPartStatus.SUCCESS, "C:000001|T:20220228-1200|R:----E0|V:20200229-143000|User String"     }, // test 222 : C,T,R,V
		{"r:----E0|t:20220228-1200|v:20200229-143000|c:000001|User String",      normalizeFPartStatus.SUCCESS, "C:000001|T:20220228-1200|R:----E0|V:20200229-143000|User String"     }, // test 223 : C,T,R,V
		{"r:----E0|v:20200229-143000|c:000001|t:20220228-1200|User String",      normalizeFPartStatus.SUCCESS, "C:000001|T:20220228-1200|R:----E0|V:20200229-143000|User String"     }, // test 224 : C,T,R,V
		{"r:----E0|v:20200229-143000|t:20220228-1200|c:000001|User String",      normalizeFPartStatus.SUCCESS, "C:000001|T:20220228-1200|R:----E0|V:20200229-143000|User String"     }, // test 225 : C,T,R,V
		{"v:20200229-143000|c:000001|t:20220228-1200|r:----E0|User String",      normalizeFPartStatus.SUCCESS, "C:000001|T:20220228-1200|R:----E0|V:20200229-143000|User String"     }, // test 226 : C,T,R,V
		{"v:20200229-143000|c:000001|r:----E0|t:20220228-1200|User String",      normalizeFPartStatus.SUCCESS, "C:000001|T:20220228-1200|R:----E0|V:20200229-143000|User String"     }, // test 227 : C,T,R,V
		{"v:20200229-143000|t:20220228-1200|c:000001|r:----E0|User String",      normalizeFPartStatus.SUCCESS, "C:000001|T:20220228-1200|R:----E0|V:20200229-143000|User String"     }, // test 228 : C,T,R,V
		{"v:20200229-143000|t:20220228-1200|r:----E0|c:000001|User String",      normalizeFPartStatus.SUCCESS, "C:000001|T:20220228-1200|R:----E0|V:20200229-143000|User String"     }, // test 229 : C,T,R,V
		{"v:20200229-143000|r:----E0|c:000001|t:20220228-1200|User String",      normalizeFPartStatus.SUCCESS, "C:000001|T:20220228-1200|R:----E0|V:20200229-143000|User String"     }, // test 230 : C,T,R,V
		{"v:20200229-143000|r:----E0|t:20220228-1200|c:000001|User String",      normalizeFPartStatus.SUCCESS, "C:000001|T:20220228-1200|R:----E0|V:20200229-143000|User String"     }, // test 231 : C,T,R,V
		{"n:ResSim Only|t:20220228-1200|r:----E0|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 232 : N,T,R,V
		{"n:ResSim Only|t:20220228-1200|v:20200229-143000|r:----E0|User String", normalizeFPartStatus.SUCCESS, "N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 233 : N,T,R,V
		{"n:ResSim Only|r:----E0|t:20220228-1200|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 234 : N,T,R,V
		{"n:ResSim Only|r:----E0|v:20200229-143000|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 235 : N,T,R,V
		{"n:ResSim Only|v:20200229-143000|t:20220228-1200|r:----E0|User String", normalizeFPartStatus.SUCCESS, "N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 236 : N,T,R,V
		{"n:ResSim Only|v:20200229-143000|r:----E0|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 237 : N,T,R,V
		{"t:20220228-1200|n:ResSim Only|r:----E0|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 238 : N,T,R,V
		{"t:20220228-1200|n:ResSim Only|v:20200229-143000|r:----E0|User String", normalizeFPartStatus.SUCCESS, "N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 239 : N,T,R,V
		{"t:20220228-1200|r:----E0|n:ResSim Only|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 240 : N,T,R,V
		{"t:20220228-1200|r:----E0|v:20200229-143000|n:ResSim Only|User String", normalizeFPartStatus.SUCCESS, "N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 241 : N,T,R,V
		{"t:20220228-1200|v:20200229-143000|n:ResSim Only|r:----E0|User String", normalizeFPartStatus.SUCCESS, "N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 242 : N,T,R,V
		{"t:20220228-1200|v:20200229-143000|r:----E0|n:ResSim Only|User String", normalizeFPartStatus.SUCCESS, "N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 243 : N,T,R,V
		{"r:----E0|n:ResSim Only|t:20220228-1200|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 244 : N,T,R,V
		{"r:----E0|n:ResSim Only|v:20200229-143000|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 245 : N,T,R,V
		{"r:----E0|t:20220228-1200|n:ResSim Only|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 246 : N,T,R,V
		{"r:----E0|t:20220228-1200|v:20200229-143000|n:ResSim Only|User String", normalizeFPartStatus.SUCCESS, "N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 247 : N,T,R,V
		{"r:----E0|v:20200229-143000|n:ResSim Only|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 248 : N,T,R,V
		{"r:----E0|v:20200229-143000|t:20220228-1200|n:ResSim Only|User String", normalizeFPartStatus.SUCCESS, "N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 249 : N,T,R,V
		{"v:20200229-143000|n:ResSim Only|t:20220228-1200|r:----E0|User String", normalizeFPartStatus.SUCCESS, "N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 250 : N,T,R,V
		{"v:20200229-143000|n:ResSim Only|r:----E0|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 251 : N,T,R,V
		{"v:20200229-143000|t:20220228-1200|n:ResSim Only|r:----E0|User String", normalizeFPartStatus.SUCCESS, "N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 252 : N,T,R,V
		{"v:20200229-143000|t:20220228-1200|r:----E0|n:ResSim Only|User String", normalizeFPartStatus.SUCCESS, "N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 253 : N,T,R,V
		{"v:20200229-143000|r:----E0|n:ResSim Only|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 254 : N,T,R,V
		{"v:20200229-143000|r:----E0|t:20220228-1200|n:ResSim Only|User String", normalizeFPartStatus.SUCCESS, "N:ResSim Only|T:20220228-1200|R:----E0|V:20200229-143000|User String"}, // test 255 : N,T,R,V
		//--------------------------//
		// 5 tags taken 3 at a time //
		//--------------------------//
		{"c:000001|n:ResSim Only|t:20220228-1200|User String",          normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|User String"         }, // test 256 : C,N,T
		{"c:000001|t:20220228-1200|n:ResSim Only|User String",          normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|User String"         }, // test 257 : C,N,T
		{"n:ResSim Only|c:000001|t:20220228-1200|User String",          normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|User String"         }, // test 258 : C,N,T
		{"n:ResSim Only|t:20220228-1200|c:000001|User String",          normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|User String"         }, // test 259 : C,N,T
		{"t:20220228-1200|c:000001|n:ResSim Only|User String",          normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|User String"         }, // test 260 : C,N,T
		{"t:20220228-1200|n:ResSim Only|c:000001|User String",          normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|T:20220228-1200|User String"         }, // test 261 : C,N,T
		{"c:000001|n:ResSim Only|r:----E0|User String",                 normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|R:----E0|User String"                }, // test 262 : C,N,R
		{"c:000001|r:----E0|n:ResSim Only|User String",                 normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|R:----E0|User String"                }, // test 263 : C,N,R
		{"n:ResSim Only|c:000001|r:----E0|User String",                 normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|R:----E0|User String"                }, // test 264 : C,N,R
		{"n:ResSim Only|r:----E0|c:000001|User String",                 normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|R:----E0|User String"                }, // test 265 : C,N,R
		{"r:----E0|c:000001|n:ResSim Only|User String",                 normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|R:----E0|User String"                }, // test 266 : C,N,R
		{"r:----E0|n:ResSim Only|c:000001|User String",                 normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|R:----E0|User String"                }, // test 267 : C,N,R
		{"c:000001|n:ResSim Only|v:20200229-143000|User String",        normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|V:20200229-143000|User String"       }, // test 268 : C,N,V
		{"c:000001|v:20200229-143000|n:ResSim Only|User String",        normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|V:20200229-143000|User String"       }, // test 269 : C,N,V
		{"n:ResSim Only|c:000001|v:20200229-143000|User String",        normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|V:20200229-143000|User String"       }, // test 270 : C,N,V
		{"n:ResSim Only|v:20200229-143000|c:000001|User String",        normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|V:20200229-143000|User String"       }, // test 271 : C,N,V
		{"v:20200229-143000|c:000001|n:ResSim Only|User String",        normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|V:20200229-143000|User String"       }, // test 272 : C,N,V
		{"v:20200229-143000|n:ResSim Only|c:000001|User String",        normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|V:20200229-143000|User String"       }, // test 273 : C,N,V
		{"c:000001|t:20220228-1200|r:----E0|User String",               normalizeFPartStatus.SUCCESS, "C:000001|T:20220228-1200|R:----E0|User String"              }, // test 274 : C,T,R
		{"c:000001|r:----E0|t:20220228-1200|User String",               normalizeFPartStatus.SUCCESS, "C:000001|T:20220228-1200|R:----E0|User String"              }, // test 275 : C,T,R
		{"t:20220228-1200|c:000001|r:----E0|User String",               normalizeFPartStatus.SUCCESS, "C:000001|T:20220228-1200|R:----E0|User String"              }, // test 276 : C,T,R
		{"t:20220228-1200|r:----E0|c:000001|User String",               normalizeFPartStatus.SUCCESS, "C:000001|T:20220228-1200|R:----E0|User String"              }, // test 277 : C,T,R
		{"r:----E0|c:000001|t:20220228-1200|User String",               normalizeFPartStatus.SUCCESS, "C:000001|T:20220228-1200|R:----E0|User String"              }, // test 278 : C,T,R
		{"r:----E0|t:20220228-1200|c:000001|User String",               normalizeFPartStatus.SUCCESS, "C:000001|T:20220228-1200|R:----E0|User String"              }, // test 279 : C,T,R
		{"c:000001|t:20220228-1200|v:20200229-143000|User String",      normalizeFPartStatus.SUCCESS, "C:000001|T:20220228-1200|V:20200229-143000|User String"     }, // test 280 : C,T,V
		{"c:000001|v:20200229-143000|t:20220228-1200|User String",      normalizeFPartStatus.SUCCESS, "C:000001|T:20220228-1200|V:20200229-143000|User String"     }, // test 281 : C,T,V
		{"t:20220228-1200|c:000001|v:20200229-143000|User String",      normalizeFPartStatus.SUCCESS, "C:000001|T:20220228-1200|V:20200229-143000|User String"     }, // test 282 : C,T,V
		{"t:20220228-1200|v:20200229-143000|c:000001|User String",      normalizeFPartStatus.SUCCESS, "C:000001|T:20220228-1200|V:20200229-143000|User String"     }, // test 283 : C,T,V
		{"v:20200229-143000|c:000001|t:20220228-1200|User String",      normalizeFPartStatus.SUCCESS, "C:000001|T:20220228-1200|V:20200229-143000|User String"     }, // test 284 : C,T,V
		{"v:20200229-143000|t:20220228-1200|c:000001|User String",      normalizeFPartStatus.SUCCESS, "C:000001|T:20220228-1200|V:20200229-143000|User String"     }, // test 285 : C,T,V
		{"c:000001|r:----E0|v:20200229-143000|User String",             normalizeFPartStatus.SUCCESS, "C:000001|R:----E0|V:20200229-143000|User String"            }, // test 286 : C,R,V
		{"c:000001|v:20200229-143000|r:----E0|User String",             normalizeFPartStatus.SUCCESS, "C:000001|R:----E0|V:20200229-143000|User String"            }, // test 287 : C,R,V
		{"r:----E0|c:000001|v:20200229-143000|User String",             normalizeFPartStatus.SUCCESS, "C:000001|R:----E0|V:20200229-143000|User String"            }, // test 288 : C,R,V
		{"r:----E0|v:20200229-143000|c:000001|User String",             normalizeFPartStatus.SUCCESS, "C:000001|R:----E0|V:20200229-143000|User String"            }, // test 289 : C,R,V
		{"v:20200229-143000|c:000001|r:----E0|User String",             normalizeFPartStatus.SUCCESS, "C:000001|R:----E0|V:20200229-143000|User String"            }, // test 290 : C,R,V
		{"v:20200229-143000|r:----E0|c:000001|User String",             normalizeFPartStatus.SUCCESS, "C:000001|R:----E0|V:20200229-143000|User String"            }, // test 291 : C,R,V
		{"n:ResSim Only|t:20220228-1200|r:----E0|User String",          normalizeFPartStatus.SUCCESS, "N:ResSim Only|T:20220228-1200|R:----E0|User String"         }, // test 292 : N,T,R
		{"n:ResSim Only|r:----E0|t:20220228-1200|User String",          normalizeFPartStatus.SUCCESS, "N:ResSim Only|T:20220228-1200|R:----E0|User String"         }, // test 293 : N,T,R
		{"t:20220228-1200|n:ResSim Only|r:----E0|User String",          normalizeFPartStatus.SUCCESS, "N:ResSim Only|T:20220228-1200|R:----E0|User String"         }, // test 294 : N,T,R
		{"t:20220228-1200|r:----E0|n:ResSim Only|User String",          normalizeFPartStatus.SUCCESS, "N:ResSim Only|T:20220228-1200|R:----E0|User String"         }, // test 295 : N,T,R
		{"r:----E0|n:ResSim Only|t:20220228-1200|User String",          normalizeFPartStatus.SUCCESS, "N:ResSim Only|T:20220228-1200|R:----E0|User String"         }, // test 296 : N,T,R
		{"r:----E0|t:20220228-1200|n:ResSim Only|User String",          normalizeFPartStatus.SUCCESS, "N:ResSim Only|T:20220228-1200|R:----E0|User String"         }, // test 297 : N,T,R
		{"n:ResSim Only|t:20220228-1200|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "N:ResSim Only|T:20220228-1200|V:20200229-143000|User String"}, // test 298 : N,T,V
		{"n:ResSim Only|v:20200229-143000|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "N:ResSim Only|T:20220228-1200|V:20200229-143000|User String"}, // test 299 : N,T,V
		{"t:20220228-1200|n:ResSim Only|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "N:ResSim Only|T:20220228-1200|V:20200229-143000|User String"}, // test 300 : N,T,V
		{"t:20220228-1200|v:20200229-143000|n:ResSim Only|User String", normalizeFPartStatus.SUCCESS, "N:ResSim Only|T:20220228-1200|V:20200229-143000|User String"}, // test 301 : N,T,V
		{"v:20200229-143000|n:ResSim Only|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "N:ResSim Only|T:20220228-1200|V:20200229-143000|User String"}, // test 302 : N,T,V
		{"v:20200229-143000|t:20220228-1200|n:ResSim Only|User String", normalizeFPartStatus.SUCCESS, "N:ResSim Only|T:20220228-1200|V:20200229-143000|User String"}, // test 303 : N,T,V
		{"n:ResSim Only|r:----E0|v:20200229-143000|User String",        normalizeFPartStatus.SUCCESS, "N:ResSim Only|R:----E0|V:20200229-143000|User String"       }, // test 304 : N,R,V
		{"n:ResSim Only|v:20200229-143000|r:----E0|User String",        normalizeFPartStatus.SUCCESS, "N:ResSim Only|R:----E0|V:20200229-143000|User String"       }, // test 305 : N,R,V
		{"r:----E0|n:ResSim Only|v:20200229-143000|User String",        normalizeFPartStatus.SUCCESS, "N:ResSim Only|R:----E0|V:20200229-143000|User String"       }, // test 306 : N,R,V
		{"r:----E0|v:20200229-143000|n:ResSim Only|User String",        normalizeFPartStatus.SUCCESS, "N:ResSim Only|R:----E0|V:20200229-143000|User String"       }, // test 307 : N,R,V
		{"v:20200229-143000|n:ResSim Only|r:----E0|User String",        normalizeFPartStatus.SUCCESS, "N:ResSim Only|R:----E0|V:20200229-143000|User String"       }, // test 308 : N,R,V
		{"v:20200229-143000|r:----E0|n:ResSim Only|User String",        normalizeFPartStatus.SUCCESS, "N:ResSim Only|R:----E0|V:20200229-143000|User String"       }, // test 309 : N,R,V
		{"t:20220228-1200|r:----E0|v:20200229-143000|User String",      normalizeFPartStatus.SUCCESS, "T:20220228-1200|R:----E0|V:20200229-143000|User String"     }, // test 310 : T,R,V
		{"t:20220228-1200|v:20200229-143000|r:----E0|User String",      normalizeFPartStatus.SUCCESS, "T:20220228-1200|R:----E0|V:20200229-143000|User String"     }, // test 311 : T,R,V
		{"r:----E0|t:20220228-1200|v:20200229-143000|User String",      normalizeFPartStatus.SUCCESS, "T:20220228-1200|R:----E0|V:20200229-143000|User String"     }, // test 312 : T,R,V
		{"r:----E0|v:20200229-143000|t:20220228-1200|User String",      normalizeFPartStatus.SUCCESS, "T:20220228-1200|R:----E0|V:20200229-143000|User String"     }, // test 313 : T,R,V
		{"v:20200229-143000|t:20220228-1200|r:----E0|User String",      normalizeFPartStatus.SUCCESS, "T:20220228-1200|R:----E0|V:20200229-143000|User String"     }, // test 314 : T,R,V
		{"v:20200229-143000|r:----E0|t:20220228-1200|User String",      normalizeFPartStatus.SUCCESS, "T:20220228-1200|R:----E0|V:20200229-143000|User String"     }, // test 315 : T,R,V
		//--------------------------//
		// 5 tags taken 2 at a time //
		//--------------------------//
		{"c:000001|n:ResSim Only|User String",            normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|User String"           }, // test 316 : C,N
		{"n:ResSim Only|c:000001|User String",            normalizeFPartStatus.SUCCESS, "C:000001|N:ResSim Only|User String"           }, // test 317 : C,N
		{"c:000001|t:20220228-1200|User String",          normalizeFPartStatus.SUCCESS, "C:000001|T:20220228-1200|User String"         }, // test 318 : C,T
		{"t:20220228-1200|c:000001|User String",          normalizeFPartStatus.SUCCESS, "C:000001|T:20220228-1200|User String"         }, // test 319 : C,T
		{"c:000001|r:----E0|User String",                 normalizeFPartStatus.SUCCESS, "C:000001|R:----E0|User String"                }, // test 320 : C,R
		{"r:----E0|c:000001|User String",                 normalizeFPartStatus.SUCCESS, "C:000001|R:----E0|User String"                }, // test 321 : C,R
		{"c:000001|v:20200229-143000|User String",        normalizeFPartStatus.SUCCESS, "C:000001|V:20200229-143000|User String"       }, // test 322 : C,V
		{"v:20200229-143000|c:000001|User String",        normalizeFPartStatus.SUCCESS, "C:000001|V:20200229-143000|User String"       }, // test 323 : C,V
		{"n:ResSim Only|t:20220228-1200|User String",     normalizeFPartStatus.SUCCESS, "N:ResSim Only|T:20220228-1200|User String"    }, // test 324 : N,T
		{"t:20220228-1200|n:ResSim Only|User String",     normalizeFPartStatus.SUCCESS, "N:ResSim Only|T:20220228-1200|User String"    }, // test 325 : N,T
		{"n:ResSim Only|r:----E0|User String",            normalizeFPartStatus.SUCCESS, "N:ResSim Only|R:----E0|User String"           }, // test 326 : N,R
		{"r:----E0|n:ResSim Only|User String",            normalizeFPartStatus.SUCCESS, "N:ResSim Only|R:----E0|User String"           }, // test 327 : N,R
		{"n:ResSim Only|v:20200229-143000|User String",   normalizeFPartStatus.SUCCESS, "N:ResSim Only|V:20200229-143000|User String"  }, // test 328 : N,V
		{"v:20200229-143000|n:ResSim Only|User String",   normalizeFPartStatus.SUCCESS, "N:ResSim Only|V:20200229-143000|User String"  }, // test 329 : N,V
		{"t:20220228-1200|r:----E0|User String",          normalizeFPartStatus.SUCCESS, "T:20220228-1200|R:----E0|User String"         }, // test 330 : T,R
		{"r:----E0|t:20220228-1200|User String",          normalizeFPartStatus.SUCCESS, "T:20220228-1200|R:----E0|User String"         }, // test 331 : T,R
		{"t:20220228-1200|v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "T:20220228-1200|V:20200229-143000|User String"}, // test 332 : T,V
		{"v:20200229-143000|t:20220228-1200|User String", normalizeFPartStatus.SUCCESS, "T:20220228-1200|V:20200229-143000|User String"}, // test 333 : T,V
		{"r:----E0|v:20200229-143000|User String",        normalizeFPartStatus.SUCCESS, "R:----E0|V:20200229-143000|User String"       }, // test 334 : R,V
		{"v:20200229-143000|r:----E0|User String",        normalizeFPartStatus.SUCCESS, "R:----E0|V:20200229-143000|User String"       }, // test 335 : R,V
		//--------------------------//
		// 5 tags taken 1 at a time //
		//--------------------------//
		{"c:000001|User String",          normalizeFPartStatus.SUCCESS, "C:000001|User String"         }, // test 336 : C
		{"n:ResSim Only|User String",     normalizeFPartStatus.SUCCESS, "N:ResSim Only|User String"    }, // test 337 : N
		{"t:20220228-1200|User String",   normalizeFPartStatus.SUCCESS, "T:20220228-1200|User String"  }, // test 338 : T
		{"r:----E0|User String",          normalizeFPartStatus.SUCCESS, "R:----E0|User String"         }, // test 339 : R
		{"v:20200229-143000|User String", normalizeFPartStatus.SUCCESS, "V:20200229-143000|User String"}, // test 340 : V
	};
	//--------------------------------------------//
	// first test the normzlization function only //
	//--------------------------------------------//
	int status = 0;
	char* normalized = NULL;
	for (int i = 0; i < sizeof(tests) / sizeof(tests[0]); ++i) {
		int _status = normalizeFPart(&normalized, tests[i].fPart);
		printf("Test %2d : Status = %2d : %s --> %s\n", i+1, _status, tests[i].fPart, normalized);
		if (_status != tests[i].expected_status) {
			status = -1;
		}
		if (normalized) {
			if (tests[i].expected_normalized == NULL) {
				status = -1;
			}
			else if (strcmp(tests[i].expected_normalized, normalized)) {
				status = -1;
			}
			free(normalized);
		}
		else if (tests[i].expected_normalized != NULL) {
			status = -1;
		}
	}
	if (status) return status;
	//--------------------------------------//
	// now test storing and retrieving data //
	//--------------------------------------//
	long long ifltab[250] = {0};
	zStructTimeSeries* tssStore = NULL;
	zStructTimeSeries* tssRetrieve = NULL;
	char* filename = "v7_c.dss";
	char* pathname_pattern = "//TestTsLoc/Elev//1Hour/%s/";
	char pathname[MAX_PATHNAME_SIZE];
	double dvalues[6] = { 1000,1001,1002,1003,1004,1005 };
	int numberValues = 6;
	char* startDate = "01Oct2021";
	char* startTime = "01:00";
	char* endDate = "01Oct2021";
	char* endTime = "24:00";
	char* unit = "ft";
	char* type = "INST-VAL";

	remove(filename);
	status = hec_dss_zopen(ifltab, filename);
	//--------------------------------------------------------//
	// test storing/retrieveing pathnames with normal F-parts //
	//--------------------------------------------------------//
	for (int i = 0; i < 5; ++i) {
		sprintf(pathname, pathname_pattern, tests[i].fPart);
		printf("Storing to %s\n", pathname);
		tssStore = zstructTsNewRegDoubles(pathname, dvalues, numberValues, startDate, startTime, unit, type);
		status = ztsStore(ifltab, tssStore, 0);
		assert(status == 0);
		assert(!strcmp(tssStore->pathname, pathname));
		tssRetrieve = zstructTsNewTimes(pathname, startDate, startTime, endDate, endTime);
		printf("Retrieving from %s\n", pathname);
		status = ztsRetrieve(ifltab, tssRetrieve, 0, 0, 0);
		assert(status == 0);
		assert(!strcmp(tssRetrieve->pathname, pathname));
		zstructFree(tssStore);
		zstructFree(tssRetrieve);
	}
	//----------------------------------------------------------------//
	// test storing/retrieveing pathnames with invalid tagged F-parts //
	//----------------------------------------------------------------//
	for (int i = 5; i < 15; ++i) {
		sprintf(pathname, pathname_pattern, tests[i].fPart);
		printf("Storing to %s\n", pathname);
		tssStore = zstructTsNewRegDoubles(pathname, dvalues, numberValues, startDate, startTime, unit, type);
		status = ztsStore(ifltab, tssStore, 0);
		assert(status != 0);
		zset("clear", "", 0);
		tssRetrieve = zstructTsNewTimes(pathname, startDate, startTime, endDate, endTime);
		printf("Retrieving from %s\n", pathname);
		status = ztsRetrieve(ifltab, tssRetrieve, 0, 0, 0);
		assert(status != 0);
		zset("clear", "", 0);
		zstructFree(tssStore);
		zstructFree(tssRetrieve);
	}
	//-----------------------------------------------------------------------------------------------------------//
	// test storing/retrieveing pathnames with valid tagged F-parts in canonical and reverse canonical tag order //
	//-----------------------------------------------------------------------------------------------------------//
	for (int i = 15; i < 340; ++i) {
		sprintf(pathname, pathname_pattern, tests[i].fPart);
		printf("Storing to %s\n", pathname);
		tssStore = zstructTsNewRegDoubles(pathname, dvalues, numberValues, startDate, startTime, unit, type);
		status = ztsStore(ifltab, tssStore, 0);
		assert(status == 0);
		sprintf(pathname, pathname_pattern, tests[i].expected_normalized);
		assert(!strcmp(tssStore->pathname, pathname));
		sprintf(pathname, pathname_pattern, tests[i].fPart);
		printf("Retrieving from %s\n", pathname);
		tssRetrieve = zstructTsNewTimes(pathname, startDate, startTime, endDate, endTime);
		status = ztsRetrieve(ifltab, tssRetrieve, 0, 0, 0);
		assert(status == 0);
		sprintf(pathname, pathname_pattern, tests[i].expected_normalized);
		assert(!strcmp(tssRetrieve->pathname, pathname));
		zstructFree(tssStore);
		zstructFree(tssRetrieve);
	}
	zclose(ifltab);
	return status;
}
/*
Tests 16-340 were generated by this script

from itertools import combinations
from itertools import permutations
import re

tag_char_pattern = re.compile(r"\w:")

tag_chars = ["C","N","T","R","V"]
tags = {
	"C" : "C:000001",
	"N" : "N:ResSim Only",
	"T" : "T:20220228-1200",
	"R" : "R:----E0",
	"V" : "V:20200229-143000"
}

def build_f_part(chars) :
	return '"%s"' % ("|".join([tags[c] for c in chars]) + "|User String")

test_num = 15
for i in 5,4,3,2,1 :
	print("//--------------------------//")
	print("// 5 tags taken %d at a time //" % i)
	print("//--------------------------//")
	for _pass in 1, 2 :
		if _pass == 1 :
			actual_len = 0
			expected_len = 0
		for items in list(combinations(tag_chars, i)) :
			expected = build_f_part(items)
			if _pass == 1 :
				if len(expected) > expected_len : expected_len = len(expected)
			for perm in list(permutations(items)) :
				actual = "%s," % build_f_part(perm)
				actual = re.sub(tag_char_pattern, lambda m : m.group(0).lower() , actual)
				if _pass == 1 :
					if len(actual) > actual_len : actual_len = len(actual)
				else :
					test_num += 1
					print('{%s normalizeFPartStatus.SUCCESS, %s}, // test %d : %s' % (
						actual.ljust(actual_len), 
						expected.ljust(expected_len), 
						test_num,
						",".join(items)))
*/
