      SUBROUTINE ZRPDI (IFLTAB, CPATH, NORD, NCURVE, IHORIZ,
     * C1UNIT, C1TYPE, C2UNIT, C2TYPE, SVALUES, DVALUES,
     * LDOUBLE, KVALS, NVALS, CLABEL, KLABEL, LABEL,
     * IUHEAD, KUHEAD, NUHEAD, ISTAT)
C
      implicit none
C
C     Retrieve Paired Data
C
C
      INTEGER IFLTAB(*), IUHEAD(*),zdssVersion,KLABEL
      INTEGER NORD, NCURVE, IHORIZ, KVALS, NVALS, KUHEAD, NUHEAD, ISTAT
      CHARACTER CPATH*(*), CLABEL(*)*(*)
      CHARACTER C1UNIT*(*), C1TYPE*(*), C2UNIT*(*), C2TYPE*(*)
      REAL SVALUES(*)
      DOUBLE PRECISION DVALUES(*)
      LOGICAL LDOUBLE, LABEL
C
      IF (zdssVersion(IFLTAB).EQ.6) THEN
          CALL ZRPDI6 (IFLTAB, CPATH, NORD, NCURVE, IHORIZ,
     *    C1UNIT, C1TYPE, C2UNIT, C2TYPE, SVALUES, DVALUES,
     *    LDOUBLE, KVALS, NVALS, CLABEL, KLABEL, LABEL,
     *    IUHEAD, KUHEAD, NUHEAD, ISTAT)
      ELSE
          CALL ZRPDI7 (IFLTAB, CPATH, NORD, NCURVE, IHORIZ,
     *    C1UNIT, C1TYPE, C2UNIT, C2TYPE, SVALUES, DVALUES,
     *    LDOUBLE, KVALS, NVALS, CLABEL, KLABEL, LABEL,
     *    IUHEAD, KUHEAD, NUHEAD, ISTAT)
      ENDIF
C
      RETURN
      END

