      SUBROUTINE zrpd (IFLTAB, CPATH, NORD, NCURVE, IHORIZ,
     * C1UNIT, C1TYPE, C2UNIT, C2TYPE, SVALUES, KVALS, NVALS,
     * CLABEL, KLABEL, LABEL, IUHEAD, KUHEAD, NUHEAD, ISTAT)
C
      implicit none
C
C     Retrieve Paired Data
C
C     Written by Bill Charley at HEC, 1989
C
C
      INTEGER IFLTAB(*), IUHEAD(*)
      integer zdssVersion,NORD,NCURVE,IHORIZ,KVALS,NVALS,KLABEL,KUHEAD
      integer NUHEAD,ISTAT
      CHARACTER CPATH*(*), CLABEL(*)*(*)
      CHARACTER C1UNIT*(*), C1TYPE*(*), C2UNIT*(*), C2TYPE*(*)
      REAL SVALUES(*)
      DOUBLE PRECISION DVALUES(1)
      LOGICAL LABEL
C
C
      IF (zdssVersion(IFLTAB).EQ.6) THEN
          CALL ZRPDI6 (IFLTAB, CPATH, NORD, NCURVE, IHORIZ,
     *    C1UNIT, C1TYPE, C2UNIT, C2TYPE, SVALUES, DVALUES,
     *    .FALSE., KVALS, NVALS, CLABEL, KLABEL, LABEL,
     *    IUHEAD, KUHEAD, NUHEAD, ISTAT)
      ELSE
          CALL ZRPDI7 (IFLTAB, CPATH, NORD, NCURVE, IHORIZ,
     *    C1UNIT, C1TYPE, C2UNIT, C2TYPE, SVALUES, DVALUES,
     *    .FALSE., KVALS, NVALS, CLABEL, KLABEL, LABEL,
     *    IUHEAD, KUHEAD, NUHEAD, ISTAT)
      ENDIF
C
      RETURN
C
      END

