      SUBROUTINE zrrtsc (IFLTAB, CPATH, CDATE, CTIME, KVALS, NVALS,
     * LGETDOB, LFILDOB, SVALUES, DVALUES, JQUAL, LQUAL, LQREAD,
     * CUNITS, CTYPE, CSUPP, IOFSET, JCOMP,
     * ITZONE, CTZONE, COORDS, ICDESC, LCOORDS, ISTAT)
C
C     Z-Retrieve Regular interval Time-Series data
C
      implicit none
C
      CHARACTER CPATH*(*), CTYPE*(*), CUNITS*(*), CDATE*(*), CTIME*(*)
      CHARACTER CSUPP*(*), CTZONE*(*)
      INTEGER IFLTAB(*), JQUAL(*), ICDESC(*), ITZONE
      INTEGER KVALS, NVALS, IOFSET, JCOMP, ISTAT
      integer zdssVersion
      REAL SVALUES(*)
      DOUBLE PRECISION DVALUES(*), COORDS(*)
      LOGICAL LGETDOB, LFILDOB, LCOORDS, LQUAL, LQREAD

C
      IF (zdssVersion(IFLTAB).EQ.6) THEN
         CALL zrrtsc6 (IFLTAB, CPATH, CDATE, CTIME, KVALS, NVALS,
     *   LGETDOB, LFILDOB, SVALUES, DVALUES, JQUAL, LQUAL, LQREAD,
     *   CUNITS, CTYPE, CSUPP, IOFSET, JCOMP,
     *   ITZONE, CTZONE, COORDS, ICDESC, LCOORDS, ISTAT)
      ELSE
         CALL zrrtsc7 (IFLTAB, CPATH, CDATE, CTIME, KVALS, NVALS,
     *   LGETDOB, LFILDOB, SVALUES, DVALUES, JQUAL, LQUAL, LQREAD,
     *   CUNITS, CTYPE, CSUPP, IOFSET, JCOMP,
     *   ITZONE, CTZONE, COORDS, ICDESC, LCOORDS, ISTAT)
      ENDIF
C
      RETURN
      END

