      SUBROUTINE ZSITSI(IFLTAB, CPATH, ITIMES, SVALUES, DVALUES,
     * LDOUBLE, NVALUE, IBDATE, JQUAL, LSQUAL, CUNITS, CTYPE,
     * IUHEAD, NUHEAD, COORDS, NCOORDS, ICDESC, NCDESC,INFLAG, ISTAT)
C
      implicit none
C
C     Z - Store - IRregular - Time - Series  data into DSS database
C
      INTEGER IFLTAB(*), JQUAL(*), ITIMES(*), IUHEAD(*),zdssVersion
      REAL SVALUES(*)
      DOUBLE PRECISION DVALUES(*), COORDS(*)
      INTEGER NVALUE, IBDATE, NCOORDS, NUHEAD, ICDESC(*)
      INTEGER NCDESC, INFLAG, ISTAT
      LOGICAL LDOUBLE, LSQUAL
C
      CHARACTER CPATH*(*), CUNITS*(*), CTYPE*(*)
C
C
      IF (zdssVersion(IFLTAB).EQ.6) THEN
          CALL ZSITSI6 (IFLTAB, CPATH, ITIMES, SVALUES, DVALUES,
     *    LDOUBLE, NVALUE, IBDATE, JQUAL, LSQUAL, CUNITS, CTYPE,
     *    IUHEAD, NUHEAD, COORDS, NCOORDS, ICDESC, NCDESC, INFLAG,
     *    ISTAT)
      ELSE
          CALL ZSITSI7 (IFLTAB, CPATH, ITIMES, SVALUES, DVALUES,
     *    LDOUBLE, NVALUE, IBDATE, JQUAL, LSQUAL, CUNITS, CTYPE,
     *    IUHEAD, NUHEAD, COORDS, NCOORDS, ICDESC, NCDESC, INFLAG,
     *    ISTAT)
      ENDIF
C
      RETURN
      END

