name: macOS Build with Intel Fortran

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build artifacts
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_21_X64 }}
          GFORTRAN_PATH: '/usr/local/opt/gcc@14/lib/gcc/14'
        run: |
          cd heclib
          make

      - name: Checkout test data
        uses: actions/checkout@v3
        with:
          repository: 'HydrologicEngineeringCenter/dss-test-data'
          path: 'dss-test-data'

      #   - name: Save artifacts
      #     uses: actions/upload-artifact@v4
      #     with:
      #       name: dss
      #       path: |
      #         ${{ github.workspace }}/hecdss.zip
      #         ${{ github.workspace }}/heclib.zip
      #         ${{ github.workspace }}/javaHeclib.zip

      - name: Elementary C tests
        run: ./test/test_c.sh

      - name: Full C tests
        run: ./test/test_Dss-C.sh

      - name: Fortran tests
        run: ./test/test_fortran.sh