name: macOS Build with Intel Fortran

on:
  push:
    branches: [ feature/update-macos-github-actions ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    # macOS 13 is the latest GitHub action runner with Intel
    # https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
    runs-on: macos-13
    env:
      JAVA_HOME: '/Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.15-6/x64/Contents/Home/'
      GFORTRAN_PATH: '/usr/local/lib/gcc/14'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build artifacts
        run: |
          cd heclib
          make

      - name: Checkout test data
        uses: actions/checkout@v3
        with:
          repository: 'HydrologicEngineeringCenter/dss-test-data'
          path: 'dss-test-data'

      #   - name: Save artifacts
      #     uses: actions/upload-artifact@v4
      #     with:
      #       name: dss
      #       path: |
      #         ${{ github.workspace }}/hecdss.zip
      #         ${{ github.workspace }}/heclib.zip
      #         ${{ github.workspace }}/javaHeclib.zip

      - name: Elementary C tests
        run: ./test/test_c.sh

      - name: Full C tests
        run: ./test/test_Dss-C.sh

      - name: Fortran tests
        run: ./test/test_fortran.sh