name: macOS Build with Intel Fortran

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    # macOS 13 is the latest GitHub action runner with Intel
    # https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
    runs-on: macos-13

    env:
      JAVA_HOME: /Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/21.0.7-6.0/x64/Contents/Home/
      GFORTRAN_PATH: /usr/local/Cellar/gcc/14.2.0_1/lib/gcc/14

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: HydrologicEngineeringCenter/dss-test-data
          path: dss-test-data

      - name: Verify GCC library paths
        run: |
          echo 'ls -al /usr/local/Cellar/gcc/14.2.0_1/lib/gcc/14'
          ls -al /usr/local/Cellar/gcc/14.2.0_1/lib/gcc/14

      - name: Build main library
        run: |
          ln -sfn "$(which gfortran-14)" /usr/local/bin/gfortran
          
          echo JAVA_HOME: $JAVA_HOME
          echo GFORTRAN_PATH: $GFORTRAN_PATH
         
          gfortran --version 
          cd heclib
          make

      - name: Build and run basic C test programs
        run: |
          cd test/C
          ./unix_test

      - name: Build and run Dss-C test program
        run: |
          cd test/Dss-C
          make test