name: macOS Build with Intel Fortran

on:
  push:
    branches: [ feature/update-macos-github-actions ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    # macOS 13 is the latest GitHub action runner with Intel
    # https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
    runs-on: macos-13
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Link gfortran-14 to gfortran
        run: |
          ln -sfn "$(which gfortran-14)" /usr/local/bin/gfortran

      - name: Set JAVA_HOME to Java 21
        run: |
          echo "JAVA_HOME=${{ runner.env.JAVA_HOME_21_X64 }}" >> $GITHUB_ENV
          echo "JAVA_HOME=$JAVA_HOME"
          $JAVA_HOME/bin/java -version

      - name: Set GFORTRAN_PATH from gfortran-14
        run: |
          echo $(dirname "$(which gfortran-14)")
          GFORTRAN_BIN_PATH=$(dirname "$(which gfortran-14)")
          GFORTRAN_PATH="$GFORTRAN_BIN_PATH/../lib/gcc/14"
          echo "GFORTRAN_PATH=$GFORTRAN_PATH" >> $GITHUB_ENV
          "$GFORTRAN_PATH/../../bin/gfortran-14" --version

      - name: Build artifacts
        run: |
          cd heclib
          make

      - name: Checkout test data
        uses: actions/checkout@v3
        with:
          repository: 'HydrologicEngineeringCenter/dss-test-data'
          path: 'dss-test-data'

      #   - name: Save artifacts
      #     uses: actions/upload-artifact@v4
      #     with:
      #       name: dss
      #       path: |
      #         ${{ github.workspace }}/hecdss.zip
      #         ${{ github.workspace }}/heclib.zip
      #         ${{ github.workspace }}/javaHeclib.zip

      - name: Elementary C tests
        run: ./test/test_c.sh

      - name: Full C tests
        run: ./test/test_Dss-C.sh

      - name: Fortran tests
        run: ./test/test_fortran.sh