# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: https://github.com/HydrologicEngineeringCenter/dss-test-data.git
          path: dss-test-data

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
                      
      - name: build main library
        run: |
          cd heclib
          make -f Makefile.Linux

      - name: build and run Dss-C test program
        run: |
          cd test/Dss-C
          make -f Makefile.Linux test

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: java -version

