name: Windows Build with Intel Fortran

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: intel
          version: 2024.1

      - run: |
          echo "Fortran compiler: ${{ env.FC }}"
          echo "C compiler: ${{ env.CC }}"
          echo "C++ compiler: ${{ env.CXX }}"
                 
      - name: Run build script
        env:
          IFORT_COMPILER_LIB: ${{ env.CMPLR_ROOT }}\lib
        run: .\build.bat

      - name: checkout test data
        uses: actions/checkout@v3
        with:
          repository: 'HydrologicEngineeringCenter/dss-test-data'
          path: 'dss-test-data'

      - name: save artifacts
        uses: actions/upload-artifact@v4
        with:
         name: dss
         path: |
             ${{ github.workspace }}\hecdss.zip
             ${{ github.workspace }}\heclib.zip
             ${{ github.workspace }}\javaHeclib.zip
         
      - name: Elementary C tests
        run: .\test\test_c.bat
      - name: Full C tests
        run: .\test\test_Dss-C.bat
